#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 131
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 6

enum {
  anon_sym_COMMA = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  aux_sym_struct_name_token1 = 4,
  aux_sym_struct_name_token2 = 5,
  anon_sym_DOT = 6,
  anon_sym_EQ = 7,
  anon_sym_COLON = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_AT = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  aux_sym_tag_token1 = 14,
  aux_sym_tag_token2 = 15,
  anon_sym_BSLASH_BSLASH = 16,
  aux_sym_line_string_token1 = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_quoted_string_token1 = 19,
  anon_sym_BSLASH = 20,
  aux_sym_escape_sequence_token1 = 21,
  aux_sym_escape_sequence_token2 = 22,
  aux_sym_escape_sequence_token3 = 23,
  sym_identifier = 24,
  aux_sym_float_token1 = 25,
  aux_sym_float_token2 = 26,
  aux_sym_float_token3 = 27,
  aux_sym_float_token4 = 28,
  aux_sym_integer_token1 = 29,
  aux_sym_integer_token2 = 30,
  aux_sym_integer_token3 = 31,
  aux_sym_integer_token4 = 32,
  sym_true = 33,
  sym_false = 34,
  sym_null = 35,
  aux_sym_comment_token1 = 36,
  aux_sym_top_comment_token1 = 37,
  sym_document = 38,
  sym_value = 39,
  sym_top_level_struct = 40,
  sym_struct = 41,
  sym_struct_name = 42,
  sym_struct_field = 43,
  sym_map = 44,
  sym_map_field = 45,
  sym_array = 46,
  sym_array_elem = 47,
  sym_tag_string = 48,
  sym_tag = 49,
  sym_string = 50,
  sym_line_string = 51,
  sym_quoted_string = 52,
  sym_escape_sequence = 53,
  sym_float = 54,
  sym_integer = 55,
  sym_comment = 56,
  sym_top_comment = 57,
  aux_sym_top_level_struct_repeat1 = 58,
  aux_sym_struct_name_repeat1 = 59,
  aux_sym_map_repeat1 = 60,
  aux_sym_array_repeat1 = 61,
  aux_sym_tag_repeat1 = 62,
  aux_sym_string_repeat1 = 63,
  aux_sym_quoted_string_repeat1 = 64,
  aux_sym_comment_repeat1 = 65,
  aux_sym_top_comment_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_struct_name_token1] = "struct_name_token1",
  [aux_sym_struct_name_token2] = "struct_name_token2",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_tag_token1] = "tag_token1",
  [aux_sym_tag_token2] = "tag_token2",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [aux_sym_line_string_token1] = "line_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [aux_sym_escape_sequence_token2] = "escape_sequence_token2",
  [aux_sym_escape_sequence_token3] = "escape_sequence_token3",
  [sym_identifier] = "identifier",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [aux_sym_float_token3] = "float_token3",
  [aux_sym_float_token4] = "float_token4",
  [aux_sym_integer_token1] = "integer_token1",
  [aux_sym_integer_token2] = "integer_token2",
  [aux_sym_integer_token3] = "integer_token3",
  [aux_sym_integer_token4] = "integer_token4",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_top_comment_token1] = "top_comment_token1",
  [sym_document] = "document",
  [sym_value] = "value",
  [sym_top_level_struct] = "top_level_struct",
  [sym_struct] = "struct",
  [sym_struct_name] = "struct_name",
  [sym_struct_field] = "struct_field",
  [sym_map] = "map",
  [sym_map_field] = "map_field",
  [sym_array] = "array",
  [sym_array_elem] = "array_elem",
  [sym_tag_string] = "tag_string",
  [sym_tag] = "tag",
  [sym_string] = "string",
  [sym_line_string] = "line_string",
  [sym_quoted_string] = "quoted_string",
  [sym_escape_sequence] = "escape_sequence",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [sym_comment] = "comment",
  [sym_top_comment] = "top_comment",
  [aux_sym_top_level_struct_repeat1] = "top_level_struct_repeat1",
  [aux_sym_struct_name_repeat1] = "struct_name_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_top_comment_repeat1] = "top_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_struct_name_token1] = aux_sym_struct_name_token1,
  [aux_sym_struct_name_token2] = aux_sym_struct_name_token2,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_tag_token1] = aux_sym_tag_token1,
  [aux_sym_tag_token2] = aux_sym_tag_token2,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [aux_sym_line_string_token1] = aux_sym_line_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [aux_sym_escape_sequence_token2] = aux_sym_escape_sequence_token2,
  [aux_sym_escape_sequence_token3] = aux_sym_escape_sequence_token3,
  [sym_identifier] = sym_identifier,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [aux_sym_float_token3] = aux_sym_float_token3,
  [aux_sym_float_token4] = aux_sym_float_token4,
  [aux_sym_integer_token1] = aux_sym_integer_token1,
  [aux_sym_integer_token2] = aux_sym_integer_token2,
  [aux_sym_integer_token3] = aux_sym_integer_token3,
  [aux_sym_integer_token4] = aux_sym_integer_token4,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_top_comment_token1] = aux_sym_top_comment_token1,
  [sym_document] = sym_document,
  [sym_value] = sym_value,
  [sym_top_level_struct] = sym_top_level_struct,
  [sym_struct] = sym_struct,
  [sym_struct_name] = sym_struct_name,
  [sym_struct_field] = sym_struct_field,
  [sym_map] = sym_map,
  [sym_map_field] = sym_map_field,
  [sym_array] = sym_array,
  [sym_array_elem] = sym_array_elem,
  [sym_tag_string] = sym_tag_string,
  [sym_tag] = sym_tag,
  [sym_string] = sym_string,
  [sym_line_string] = sym_line_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [sym_comment] = sym_comment,
  [sym_top_comment] = sym_top_comment,
  [aux_sym_top_level_struct_repeat1] = aux_sym_top_level_struct_repeat1,
  [aux_sym_struct_name_repeat1] = aux_sym_struct_name_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_top_comment_repeat1] = aux_sym_top_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_struct_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_name_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_top_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_top_level_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_name] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_map_field] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_array_elem] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_string] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_top_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_top_level_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_top_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_key, 0},
    {field_value, 2},
  [3] =
    {field_key, 1},
    {field_value, 3},
  [5] =
    {field_name, 1},
  [6] =
    {field_key, 2},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == ',') ADVANCE(42);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '=') ADVANCE(48);
      if (lookahead == '@') ADVANCE(52);
      if (lookahead == '[') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(63);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead == '}') ADVANCE(44);
      if (lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(83);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(63);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(1);
      END_STATE();
    case 5:
      if (lookahead == '0') ADVANCE(77);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 6:
      if (lookahead == '\\') ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(19);
      if (lookahead == 'x') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(66);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == '{') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == '{') ADVANCE(37);
      END_STATE();
    case 20:
      if (lookahead == '}') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 22:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 23:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 24:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 25:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(74);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(26)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 27:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(75);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == ',') ADVANCE(42);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(77);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '@') ADVANCE(52);
      if (lookahead == '[') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'n') ADVANCE(17);
      if (lookahead == 't') ADVANCE(13);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead == '}') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(40)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_struct_name_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_struct_name_token2);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_tag_token1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_tag_token2);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_line_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_line_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token3);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '_') ADVANCE(36);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '_') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_float_token3);
      if (lookahead == '_') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_float_token4);
      if (lookahead == '_') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (lookahead == '_') ADVANCE(25);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_integer_token2);
      if (lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_integer_token3);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_integer_token4);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '_') ADVANCE(29);
      if (lookahead == 'b') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(28);
      if (lookahead == 'x') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_integer_token4);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '_') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_top_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 40},
  [3] = {.lex_state = 40},
  [4] = {.lex_state = 40},
  [5] = {.lex_state = 40},
  [6] = {.lex_state = 40},
  [7] = {.lex_state = 40},
  [8] = {.lex_state = 40},
  [9] = {.lex_state = 40},
  [10] = {.lex_state = 40},
  [11] = {.lex_state = 40},
  [12] = {.lex_state = 40},
  [13] = {.lex_state = 40},
  [14] = {.lex_state = 40},
  [15] = {.lex_state = 40},
  [16] = {.lex_state = 40},
  [17] = {.lex_state = 40},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 40},
  [20] = {.lex_state = 40},
  [21] = {.lex_state = 40},
  [22] = {.lex_state = 40},
  [23] = {.lex_state = 40},
  [24] = {.lex_state = 40},
  [25] = {.lex_state = 40},
  [26] = {.lex_state = 40},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 40},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 40},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 40},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 40},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 16},
  [89] = {.lex_state = 18},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 18},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 3},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 18},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 26},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 58},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 27},
  [127] = {.lex_state = 27},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_struct_name_token1] = ACTIONS(1),
    [aux_sym_struct_name_token2] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_tag_token1] = ACTIONS(1),
    [aux_sym_tag_token2] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_escape_sequence_token3] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [aux_sym_top_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(113),
    [sym_value] = STATE(120),
    [sym_top_level_struct] = STATE(120),
    [sym_struct] = STATE(79),
    [sym_struct_name] = STATE(111),
    [sym_struct_field] = STATE(40),
    [sym_map] = STATE(79),
    [sym_array] = STATE(79),
    [sym_tag_string] = STATE(79),
    [sym_string] = STATE(79),
    [sym_line_string] = STATE(23),
    [sym_quoted_string] = STATE(27),
    [sym_float] = STATE(79),
    [sym_integer] = STATE(79),
    [sym_comment] = STATE(114),
    [sym_top_comment] = STATE(2),
    [aux_sym_string_repeat1] = STATE(23),
    [aux_sym_comment_repeat1] = STATE(16),
    [aux_sym_top_comment_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(25),
    [sym_false] = ACTIONS(25),
    [sym_null] = ACTIONS(25),
    [aux_sym_comment_token1] = ACTIONS(27),
    [aux_sym_top_comment_token1] = ACTIONS(29),
  },
  [2] = {
    [sym_value] = STATE(124),
    [sym_top_level_struct] = STATE(124),
    [sym_struct] = STATE(79),
    [sym_struct_name] = STATE(111),
    [sym_struct_field] = STATE(40),
    [sym_map] = STATE(79),
    [sym_array] = STATE(79),
    [sym_tag_string] = STATE(79),
    [sym_string] = STATE(79),
    [sym_line_string] = STATE(23),
    [sym_quoted_string] = STATE(27),
    [sym_float] = STATE(79),
    [sym_integer] = STATE(79),
    [sym_comment] = STATE(114),
    [aux_sym_string_repeat1] = STATE(23),
    [aux_sym_comment_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(25),
    [sym_false] = ACTIONS(25),
    [sym_null] = ACTIONS(25),
    [aux_sym_comment_token1] = ACTIONS(27),
  },
  [3] = {
    [sym_value] = STATE(87),
    [sym_struct] = STATE(79),
    [sym_struct_name] = STATE(111),
    [sym_map] = STATE(79),
    [sym_array] = STATE(79),
    [sym_array_elem] = STATE(94),
    [sym_tag_string] = STATE(79),
    [sym_string] = STATE(79),
    [sym_line_string] = STATE(23),
    [sym_quoted_string] = STATE(27),
    [sym_float] = STATE(79),
    [sym_integer] = STATE(79),
    [sym_comment] = STATE(7),
    [aux_sym_string_repeat1] = STATE(23),
    [aux_sym_comment_repeat1] = STATE(16),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(33),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(25),
    [sym_false] = ACTIONS(25),
    [sym_null] = ACTIONS(25),
    [aux_sym_comment_token1] = ACTIONS(27),
  },
  [4] = {
    [sym_value] = STATE(87),
    [sym_struct] = STATE(79),
    [sym_struct_name] = STATE(111),
    [sym_map] = STATE(79),
    [sym_array] = STATE(79),
    [sym_array_elem] = STATE(94),
    [sym_tag_string] = STATE(79),
    [sym_string] = STATE(79),
    [sym_line_string] = STATE(23),
    [sym_quoted_string] = STATE(27),
    [sym_float] = STATE(79),
    [sym_integer] = STATE(79),
    [sym_comment] = STATE(8),
    [aux_sym_string_repeat1] = STATE(23),
    [aux_sym_comment_repeat1] = STATE(16),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(25),
    [sym_false] = ACTIONS(25),
    [sym_null] = ACTIONS(25),
    [aux_sym_comment_token1] = ACTIONS(27),
  },
  [5] = {
    [sym_value] = STATE(87),
    [sym_struct] = STATE(79),
    [sym_struct_name] = STATE(111),
    [sym_map] = STATE(79),
    [sym_array] = STATE(79),
    [sym_array_elem] = STATE(32),
    [sym_tag_string] = STATE(79),
    [sym_string] = STATE(79),
    [sym_line_string] = STATE(23),
    [sym_quoted_string] = STATE(27),
    [sym_float] = STATE(79),
    [sym_integer] = STATE(79),
    [sym_comment] = STATE(9),
    [aux_sym_string_repeat1] = STATE(23),
    [aux_sym_comment_repeat1] = STATE(16),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(37),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(25),
    [sym_false] = ACTIONS(25),
    [sym_null] = ACTIONS(25),
    [aux_sym_comment_token1] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    STATE(13), 1,
      sym_comment,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(87), 1,
      sym_value,
    STATE(94), 1,
      sym_array_elem,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [72] = 16,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_quoted_string,
    STATE(95), 1,
      sym_value,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [135] = 16,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_quoted_string,
    STATE(95), 1,
      sym_value,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [198] = 16,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_quoted_string,
    STATE(95), 1,
      sym_value,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [261] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(84), 1,
      sym_value,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [321] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(93), 1,
      sym_value,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [381] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(90), 1,
      sym_value,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [441] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(95), 1,
      sym_value,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [501] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(83), 1,
      sym_value,
    STATE(111), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(79), 7,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [561] = 4,
    ACTIONS(47), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    ACTIONS(45), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    ACTIONS(43), 19,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
      sym_true,
      sym_false,
      sym_null,
  [593] = 4,
    ACTIONS(54), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    ACTIONS(52), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    ACTIONS(50), 19,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
      sym_true,
      sym_false,
      sym_null,
  [625] = 4,
    ACTIONS(60), 1,
      aux_sym_top_comment_token1,
    STATE(17), 1,
      aux_sym_top_comment_repeat1,
    ACTIONS(58), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    ACTIONS(56), 18,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
      sym_true,
      sym_false,
      sym_null,
      aux_sym_comment_token1,
  [656] = 4,
    ACTIONS(67), 1,
      aux_sym_top_comment_token1,
    STATE(17), 1,
      aux_sym_top_comment_repeat1,
    ACTIONS(65), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    ACTIONS(63), 18,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
      sym_true,
      sym_false,
      sym_null,
      aux_sym_comment_token1,
  [687] = 12,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(26), 1,
      sym_comment,
    STATE(27), 1,
      sym_quoted_string,
    STATE(35), 1,
      sym_struct_field,
    STATE(36), 1,
      sym_map_field,
    STATE(125), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [725] = 10,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(29), 1,
      sym_comment,
    STATE(91), 1,
      sym_map_field,
    STATE(125), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [757] = 10,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(31), 1,
      sym_comment,
    STATE(91), 1,
      sym_map_field,
    STATE(125), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [789] = 9,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(34), 1,
      sym_comment,
    STATE(91), 1,
      sym_map_field,
    STATE(125), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [818] = 3,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [835] = 3,
    ACTIONS(79), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [852] = 1,
    ACTIONS(82), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_BSLASH_BSLASH,
      aux_sym_comment_token1,
  [863] = 7,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    ACTIONS(86), 1,
      anon_sym_DOT,
    STATE(27), 1,
      sym_quoted_string,
    STATE(108), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [886] = 1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [896] = 1,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [906] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(108), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [926] = 1,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [936] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(108), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [956] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(44), 1,
      aux_sym_array_repeat1,
    STATE(107), 1,
      sym_comment,
  [975] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(81), 1,
      aux_sym_map_repeat1,
    STATE(130), 1,
      sym_comment,
  [994] = 5,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(108), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [1011] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(98), 1,
      anon_sym_COMMA,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(45), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(123), 1,
      sym_comment,
  [1030] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(33), 1,
      aux_sym_map_repeat1,
    STATE(122), 1,
      sym_comment,
  [1049] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(82), 1,
      sym_struct_field,
    STATE(101), 1,
      sym_comment,
  [1068] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(78), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(121), 1,
      sym_comment,
  [1087] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(82), 1,
      sym_struct_field,
    STATE(99), 1,
      sym_comment,
  [1106] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(49), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(128), 1,
      sym_comment,
  [1125] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(82), 1,
      sym_struct_field,
    STATE(104), 1,
      sym_comment,
  [1144] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(82), 1,
      sym_struct_field,
    STATE(105), 1,
      sym_comment,
  [1163] = 5,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(116), 1,
      sym_string,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [1180] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(80), 1,
      aux_sym_array_repeat1,
    STATE(112), 1,
      sym_comment,
  [1199] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(78), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(117), 1,
      sym_comment,
  [1218] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(48), 1,
      sym_struct_field,
    STATE(103), 1,
      sym_comment,
  [1237] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(82), 1,
      sym_struct_field,
    STATE(100), 1,
      sym_comment,
  [1256] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(38), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(109), 1,
      sym_comment,
  [1275] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(78), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(118), 1,
      sym_comment,
  [1294] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(82), 1,
      sym_struct_field,
    STATE(106), 1,
      sym_comment,
  [1313] = 1,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1321] = 1,
    ACTIONS(138), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1329] = 1,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1337] = 1,
    ACTIONS(142), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1345] = 4,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(146), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(148), 1,
      anon_sym_BSLASH,
    STATE(72), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1359] = 1,
    ACTIONS(150), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1367] = 1,
    ACTIONS(152), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1375] = 1,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1383] = 1,
    ACTIONS(156), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1391] = 1,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1399] = 1,
    ACTIONS(160), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1407] = 1,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1415] = 1,
    ACTIONS(156), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1423] = 1,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1431] = 1,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1439] = 1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1447] = 4,
    ACTIONS(148), 1,
      anon_sym_BSLASH,
    ACTIONS(170), 1,
      anon_sym_DQUOTE,
    ACTIONS(172), 1,
      aux_sym_quoted_string_token1,
    STATE(55), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1461] = 1,
    ACTIONS(174), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1469] = 1,
    ACTIONS(176), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1477] = 1,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1485] = 1,
    ACTIONS(180), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1493] = 4,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(187), 1,
      anon_sym_BSLASH,
    STATE(72), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1507] = 1,
    ACTIONS(190), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1515] = 5,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(82), 1,
      sym_struct_field,
    STATE(114), 1,
      sym_comment,
  [1531] = 1,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1539] = 1,
    ACTIONS(194), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1547] = 1,
    ACTIONS(196), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1555] = 3,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_top_level_struct_repeat1,
    ACTIONS(198), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1567] = 1,
    ACTIONS(203), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1575] = 3,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_array_repeat1,
    ACTIONS(208), 2,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1586] = 3,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym_map_repeat1,
    ACTIONS(213), 2,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1597] = 1,
    ACTIONS(198), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1604] = 1,
    ACTIONS(215), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1611] = 1,
    ACTIONS(217), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1618] = 2,
    ACTIONS(221), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(219), 2,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
  [1626] = 3,
    ACTIONS(223), 1,
      anon_sym_LPAREN,
    ACTIONS(225), 1,
      aux_sym_tag_token2,
    STATE(86), 1,
      aux_sym_tag_repeat1,
  [1636] = 1,
    ACTIONS(228), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1642] = 1,
    ACTIONS(230), 3,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
  [1648] = 3,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      aux_sym_struct_name_token2,
    STATE(92), 1,
      aux_sym_struct_name_repeat1,
  [1658] = 1,
    ACTIONS(236), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1664] = 1,
    ACTIONS(213), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1670] = 3,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    ACTIONS(240), 1,
      aux_sym_struct_name_token2,
    STATE(92), 1,
      aux_sym_struct_name_repeat1,
  [1680] = 1,
    ACTIONS(243), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1686] = 1,
    ACTIONS(208), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1692] = 1,
    ACTIONS(245), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1698] = 3,
    ACTIONS(247), 1,
      anon_sym_LPAREN,
    ACTIONS(249), 1,
      aux_sym_tag_token2,
    STATE(86), 1,
      aux_sym_tag_repeat1,
  [1708] = 3,
    ACTIONS(251), 1,
      anon_sym_LPAREN,
    ACTIONS(253), 1,
      aux_sym_tag_token2,
    STATE(96), 1,
      aux_sym_tag_repeat1,
  [1718] = 3,
    ACTIONS(255), 1,
      anon_sym_LBRACE,
    ACTIONS(257), 1,
      aux_sym_struct_name_token2,
    STATE(89), 1,
      aux_sym_struct_name_repeat1,
  [1728] = 2,
    ACTIONS(86), 1,
      anon_sym_DOT,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
  [1735] = 2,
    ACTIONS(86), 1,
      anon_sym_DOT,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
  [1742] = 2,
    ACTIONS(86), 1,
      anon_sym_DOT,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
  [1749] = 2,
    ACTIONS(261), 1,
      aux_sym_tag_token1,
    STATE(119), 1,
      sym_tag,
  [1756] = 2,
    ACTIONS(86), 1,
      anon_sym_DOT,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
  [1763] = 2,
    ACTIONS(86), 1,
      anon_sym_DOT,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
  [1770] = 2,
    ACTIONS(86), 1,
      anon_sym_DOT,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
  [1777] = 2,
    ACTIONS(86), 1,
      anon_sym_DOT,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
  [1784] = 1,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
  [1788] = 1,
    ACTIONS(267), 1,
      anon_sym_COLON,
  [1792] = 1,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
  [1796] = 1,
    ACTIONS(269), 1,
      anon_sym_EQ,
  [1800] = 1,
    ACTIONS(271), 1,
      anon_sym_LBRACE,
  [1804] = 1,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
  [1808] = 1,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
  [1812] = 1,
    ACTIONS(86), 1,
      anon_sym_DOT,
  [1816] = 1,
    ACTIONS(275), 1,
      aux_sym_line_string_token1,
  [1820] = 1,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
  [1824] = 1,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
  [1828] = 1,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
  [1832] = 1,
    ACTIONS(279), 1,
      anon_sym_LPAREN,
  [1836] = 1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
  [1840] = 1,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
  [1844] = 1,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
  [1848] = 1,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
  [1852] = 1,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
  [1856] = 1,
    ACTIONS(283), 1,
      anon_sym_COLON,
  [1860] = 1,
    ACTIONS(285), 1,
      sym_identifier,
  [1864] = 1,
    ACTIONS(287), 1,
      sym_identifier,
  [1868] = 1,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
  [1872] = 1,
    ACTIONS(289), 1,
      anon_sym_EQ,
  [1876] = 1,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 135,
  [SMALL_STATE(9)] = 198,
  [SMALL_STATE(10)] = 261,
  [SMALL_STATE(11)] = 321,
  [SMALL_STATE(12)] = 381,
  [SMALL_STATE(13)] = 441,
  [SMALL_STATE(14)] = 501,
  [SMALL_STATE(15)] = 561,
  [SMALL_STATE(16)] = 593,
  [SMALL_STATE(17)] = 625,
  [SMALL_STATE(18)] = 656,
  [SMALL_STATE(19)] = 687,
  [SMALL_STATE(20)] = 725,
  [SMALL_STATE(21)] = 757,
  [SMALL_STATE(22)] = 789,
  [SMALL_STATE(23)] = 818,
  [SMALL_STATE(24)] = 835,
  [SMALL_STATE(25)] = 852,
  [SMALL_STATE(26)] = 863,
  [SMALL_STATE(27)] = 886,
  [SMALL_STATE(28)] = 896,
  [SMALL_STATE(29)] = 906,
  [SMALL_STATE(30)] = 926,
  [SMALL_STATE(31)] = 936,
  [SMALL_STATE(32)] = 956,
  [SMALL_STATE(33)] = 975,
  [SMALL_STATE(34)] = 994,
  [SMALL_STATE(35)] = 1011,
  [SMALL_STATE(36)] = 1030,
  [SMALL_STATE(37)] = 1049,
  [SMALL_STATE(38)] = 1068,
  [SMALL_STATE(39)] = 1087,
  [SMALL_STATE(40)] = 1106,
  [SMALL_STATE(41)] = 1125,
  [SMALL_STATE(42)] = 1144,
  [SMALL_STATE(43)] = 1163,
  [SMALL_STATE(44)] = 1180,
  [SMALL_STATE(45)] = 1199,
  [SMALL_STATE(46)] = 1218,
  [SMALL_STATE(47)] = 1237,
  [SMALL_STATE(48)] = 1256,
  [SMALL_STATE(49)] = 1275,
  [SMALL_STATE(50)] = 1294,
  [SMALL_STATE(51)] = 1313,
  [SMALL_STATE(52)] = 1321,
  [SMALL_STATE(53)] = 1329,
  [SMALL_STATE(54)] = 1337,
  [SMALL_STATE(55)] = 1345,
  [SMALL_STATE(56)] = 1359,
  [SMALL_STATE(57)] = 1367,
  [SMALL_STATE(58)] = 1375,
  [SMALL_STATE(59)] = 1383,
  [SMALL_STATE(60)] = 1391,
  [SMALL_STATE(61)] = 1399,
  [SMALL_STATE(62)] = 1407,
  [SMALL_STATE(63)] = 1415,
  [SMALL_STATE(64)] = 1423,
  [SMALL_STATE(65)] = 1431,
  [SMALL_STATE(66)] = 1439,
  [SMALL_STATE(67)] = 1447,
  [SMALL_STATE(68)] = 1461,
  [SMALL_STATE(69)] = 1469,
  [SMALL_STATE(70)] = 1477,
  [SMALL_STATE(71)] = 1485,
  [SMALL_STATE(72)] = 1493,
  [SMALL_STATE(73)] = 1507,
  [SMALL_STATE(74)] = 1515,
  [SMALL_STATE(75)] = 1531,
  [SMALL_STATE(76)] = 1539,
  [SMALL_STATE(77)] = 1547,
  [SMALL_STATE(78)] = 1555,
  [SMALL_STATE(79)] = 1567,
  [SMALL_STATE(80)] = 1575,
  [SMALL_STATE(81)] = 1586,
  [SMALL_STATE(82)] = 1597,
  [SMALL_STATE(83)] = 1604,
  [SMALL_STATE(84)] = 1611,
  [SMALL_STATE(85)] = 1618,
  [SMALL_STATE(86)] = 1626,
  [SMALL_STATE(87)] = 1636,
  [SMALL_STATE(88)] = 1642,
  [SMALL_STATE(89)] = 1648,
  [SMALL_STATE(90)] = 1658,
  [SMALL_STATE(91)] = 1664,
  [SMALL_STATE(92)] = 1670,
  [SMALL_STATE(93)] = 1680,
  [SMALL_STATE(94)] = 1686,
  [SMALL_STATE(95)] = 1692,
  [SMALL_STATE(96)] = 1698,
  [SMALL_STATE(97)] = 1708,
  [SMALL_STATE(98)] = 1718,
  [SMALL_STATE(99)] = 1728,
  [SMALL_STATE(100)] = 1735,
  [SMALL_STATE(101)] = 1742,
  [SMALL_STATE(102)] = 1749,
  [SMALL_STATE(103)] = 1756,
  [SMALL_STATE(104)] = 1763,
  [SMALL_STATE(105)] = 1770,
  [SMALL_STATE(106)] = 1777,
  [SMALL_STATE(107)] = 1784,
  [SMALL_STATE(108)] = 1788,
  [SMALL_STATE(109)] = 1792,
  [SMALL_STATE(110)] = 1796,
  [SMALL_STATE(111)] = 1800,
  [SMALL_STATE(112)] = 1804,
  [SMALL_STATE(113)] = 1808,
  [SMALL_STATE(114)] = 1812,
  [SMALL_STATE(115)] = 1816,
  [SMALL_STATE(116)] = 1820,
  [SMALL_STATE(117)] = 1824,
  [SMALL_STATE(118)] = 1828,
  [SMALL_STATE(119)] = 1832,
  [SMALL_STATE(120)] = 1836,
  [SMALL_STATE(121)] = 1840,
  [SMALL_STATE(122)] = 1844,
  [SMALL_STATE(123)] = 1848,
  [SMALL_STATE(124)] = 1852,
  [SMALL_STATE(125)] = 1856,
  [SMALL_STATE(126)] = 1860,
  [SMALL_STATE(127)] = 1864,
  [SMALL_STATE(128)] = 1868,
  [SMALL_STATE(129)] = 1872,
  [SMALL_STATE(130)] = 1876,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(15),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_top_comment_repeat1, 2),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_top_comment_repeat1, 2),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_top_comment_repeat1, 2), SHIFT_REPEAT(17),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_comment, 1),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_top_comment, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(115),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_string, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, .production_id = 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, .production_id = 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, .production_id = 1),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 6),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 6),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, .production_id = 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_string, 5, .production_id = 4),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 5),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(72),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(88),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, .production_id = 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_top_level_struct_repeat1, 2),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_top_level_struct_repeat1, 2), SHIFT_REPEAT(74),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(6),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(22),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, .production_id = 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 5, .production_id = 5),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(86),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_elem, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_name, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_field, 3, .production_id = 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_name_repeat1, 2),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_name_repeat1, 2), SHIFT_REPEAT(92),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_field, 4, .production_id = 3),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_elem, 2),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_name, 1),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 4),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [273] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ziggy(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
