#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 124
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 6

enum {
  anon_sym_COMMA = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  aux_sym_struct_name_token1 = 4,
  aux_sym_struct_name_token2 = 5,
  anon_sym_DOT = 6,
  anon_sym_EQ = 7,
  anon_sym_COLON = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_AT = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  aux_sym_tag_token1 = 14,
  aux_sym_tag_token2 = 15,
  anon_sym_BSLASH_BSLASH = 16,
  aux_sym_line_string_token1 = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_quoted_string_token1 = 19,
  anon_sym_BSLASH = 20,
  aux_sym_escape_sequence_token1 = 21,
  aux_sym_escape_sequence_token2 = 22,
  aux_sym_escape_sequence_token3 = 23,
  sym_identifier = 24,
  sym_number = 25,
  sym_true = 26,
  sym_false = 27,
  sym_null = 28,
  aux_sym_comment_token1 = 29,
  sym_document = 30,
  sym__value = 31,
  sym_top_level_struct = 32,
  sym_struct = 33,
  sym_struct_name = 34,
  sym_struct_field = 35,
  sym_map = 36,
  sym_map_field = 37,
  sym_array = 38,
  sym_array_elem = 39,
  sym_tag_string = 40,
  sym_tag = 41,
  sym_string = 42,
  sym_line_string = 43,
  sym_quoted_string = 44,
  sym_escape_sequence = 45,
  sym_comment = 46,
  aux_sym_top_level_struct_repeat1 = 47,
  aux_sym_struct_name_repeat1 = 48,
  aux_sym_map_repeat1 = 49,
  aux_sym_array_repeat1 = 50,
  aux_sym_tag_repeat1 = 51,
  aux_sym_string_repeat1 = 52,
  aux_sym_quoted_string_repeat1 = 53,
  aux_sym_comment_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_struct_name_token1] = "struct_name_token1",
  [aux_sym_struct_name_token2] = "struct_name_token2",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_tag_token1] = "tag_token1",
  [aux_sym_tag_token2] = "tag_token2",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [aux_sym_line_string_token1] = "line_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [aux_sym_escape_sequence_token2] = "escape_sequence_token2",
  [aux_sym_escape_sequence_token3] = "escape_sequence_token3",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_document] = "document",
  [sym__value] = "_value",
  [sym_top_level_struct] = "top_level_struct",
  [sym_struct] = "struct",
  [sym_struct_name] = "struct_name",
  [sym_struct_field] = "struct_field",
  [sym_map] = "map",
  [sym_map_field] = "map_field",
  [sym_array] = "array",
  [sym_array_elem] = "array_elem",
  [sym_tag_string] = "tag_string",
  [sym_tag] = "tag",
  [sym_string] = "string",
  [sym_line_string] = "line_string",
  [sym_quoted_string] = "quoted_string",
  [sym_escape_sequence] = "escape_sequence",
  [sym_comment] = "comment",
  [aux_sym_top_level_struct_repeat1] = "top_level_struct_repeat1",
  [aux_sym_struct_name_repeat1] = "struct_name_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_struct_name_token1] = aux_sym_struct_name_token1,
  [aux_sym_struct_name_token2] = aux_sym_struct_name_token2,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_tag_token1] = aux_sym_tag_token1,
  [aux_sym_tag_token2] = aux_sym_tag_token2,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [aux_sym_line_string_token1] = aux_sym_line_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [aux_sym_escape_sequence_token2] = aux_sym_escape_sequence_token2,
  [aux_sym_escape_sequence_token3] = aux_sym_escape_sequence_token3,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_document] = sym_document,
  [sym__value] = sym__value,
  [sym_top_level_struct] = sym_top_level_struct,
  [sym_struct] = sym_struct,
  [sym_struct_name] = sym_struct_name,
  [sym_struct_field] = sym_struct_field,
  [sym_map] = sym_map,
  [sym_map_field] = sym_map_field,
  [sym_array] = sym_array,
  [sym_array_elem] = sym_array_elem,
  [sym_tag_string] = sym_tag_string,
  [sym_tag] = sym_tag,
  [sym_string] = sym_string,
  [sym_line_string] = sym_line_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_comment] = sym_comment,
  [aux_sym_top_level_struct_repeat1] = aux_sym_top_level_struct_repeat1,
  [aux_sym_struct_name_repeat1] = aux_sym_struct_name_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_struct_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_name_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_top_level_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_name] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_map_field] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_array_elem] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_string] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_top_level_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_key, 0},
    {field_value, 2},
  [3] =
    {field_key, 1},
    {field_value, 3},
  [5] =
    {field_name, 1},
  [6] =
    {field_key, 2},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(53);
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == ',') ADVANCE(29);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '[') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(50);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(33);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(62);
      END_STATE();
    case 5:
      if (lookahead == '0') ADVANCE(55);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 6:
      if (lookahead == '\\') ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(19);
      if (lookahead == 'x') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(53);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == '{') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == '}') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(21)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 22:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == ',') ADVANCE(29);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(55);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '[') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'n') ADVANCE(17);
      if (lookahead == 't') ADVANCE(13);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_struct_name_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_struct_name_token2);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_tag_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_tag_token2);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_line_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_line_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token3);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 27},
  [3] = {.lex_state = 27},
  [4] = {.lex_state = 27},
  [5] = {.lex_state = 27},
  [6] = {.lex_state = 27},
  [7] = {.lex_state = 27},
  [8] = {.lex_state = 27},
  [9] = {.lex_state = 27},
  [10] = {.lex_state = 27},
  [11] = {.lex_state = 27},
  [12] = {.lex_state = 27},
  [13] = {.lex_state = 27},
  [14] = {.lex_state = 27},
  [15] = {.lex_state = 27},
  [16] = {.lex_state = 27},
  [17] = {.lex_state = 27},
  [18] = {.lex_state = 27},
  [19] = {.lex_state = 27},
  [20] = {.lex_state = 27},
  [21] = {.lex_state = 27},
  [22] = {.lex_state = 27},
  [23] = {.lex_state = 27},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 27},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 27},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 27},
  [46] = {.lex_state = 27},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 18},
  [81] = {.lex_state = 16},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 18},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 18},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 21},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 45},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 22},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 22},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_struct_name_token1] = ACTIONS(1),
    [aux_sym_struct_name_token2] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_tag_token1] = ACTIONS(1),
    [aux_sym_tag_token2] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_escape_sequence_token3] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(108),
    [sym__value] = STATE(105),
    [sym_top_level_struct] = STATE(105),
    [sym_struct] = STATE(105),
    [sym_struct_name] = STATE(104),
    [sym_struct_field] = STATE(42),
    [sym_map] = STATE(105),
    [sym_array] = STATE(105),
    [sym_tag_string] = STATE(105),
    [sym_string] = STATE(105),
    [sym_line_string] = STATE(19),
    [sym_quoted_string] = STATE(27),
    [sym_comment] = STATE(102),
    [aux_sym_string_repeat1] = STATE(19),
    [aux_sym_comment_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_true] = ACTIONS(19),
    [sym_false] = ACTIONS(19),
    [sym_null] = ACTIONS(19),
    [aux_sym_comment_token1] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    STATE(6), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(40), 1,
      sym_array_elem,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(84), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [58] = 16,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(88), 1,
      sym_array_elem,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(84), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [116] = 16,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    STATE(7), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(88), 1,
      sym_array_elem,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(84), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [174] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    STATE(9), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(88), 1,
      sym_array_elem,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(25), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(84), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [229] = 12,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_quoted_string,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(33), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(92), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [275] = 12,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_quoted_string,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(33), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(92), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [321] = 12,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_quoted_string,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(33), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(92), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [367] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(33), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(92), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [410] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(37), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(77), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [453] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(39), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(79), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [496] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(41), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(76), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [539] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(104), 1,
      sym_struct_name,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(43), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
    STATE(85), 6,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
  [582] = 3,
    ACTIONS(47), 1,
      aux_sym_comment_token1,
    STATE(14), 1,
      aux_sym_comment_repeat1,
    ACTIONS(45), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [605] = 3,
    ACTIONS(52), 1,
      aux_sym_comment_token1,
    STATE(14), 1,
      aux_sym_comment_repeat1,
    ACTIONS(50), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [628] = 12,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(23), 1,
      sym_comment,
    STATE(27), 1,
      sym_quoted_string,
    STATE(29), 1,
      sym_map_field,
    STATE(33), 1,
      sym_struct_field,
    STATE(112), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [666] = 10,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(28), 1,
      sym_comment,
    STATE(82), 1,
      sym_map_field,
    STATE(112), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [698] = 10,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(26), 1,
      sym_comment,
    STATE(27), 1,
      sym_quoted_string,
    STATE(82), 1,
      sym_map_field,
    STATE(112), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [730] = 3,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(20), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [747] = 3,
    ACTIONS(64), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(20), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [764] = 9,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(27), 1,
      sym_quoted_string,
    STATE(45), 1,
      sym_comment,
    STATE(82), 1,
      sym_map_field,
    STATE(112), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [793] = 1,
    ACTIONS(67), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_BSLASH_BSLASH,
      aux_sym_comment_token1,
  [804] = 7,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 1,
      anon_sym_DOT,
    STATE(27), 1,
      sym_quoted_string,
    STATE(121), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [827] = 1,
    ACTIONS(73), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [837] = 1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [847] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(121), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [867] = 1,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [877] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(121), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [897] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(36), 1,
      aux_sym_map_repeat1,
    STATE(123), 1,
      sym_comment,
  [916] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(75), 1,
      sym_struct_field,
    STATE(94), 1,
      sym_comment,
  [935] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(75), 1,
      sym_struct_field,
    STATE(98), 1,
      sym_comment,
  [954] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(39), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(122), 1,
      sym_comment,
  [973] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(44), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(101), 1,
      sym_comment,
  [992] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(32), 1,
      sym_struct_field,
    STATE(93), 1,
      sym_comment,
  [1011] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(75), 1,
      sym_struct_field,
    STATE(97), 1,
      sym_comment,
  [1030] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(74), 1,
      aux_sym_map_repeat1,
    STATE(103), 1,
      sym_comment,
  [1049] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(71), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(111), 1,
      sym_comment,
  [1068] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(75), 1,
      sym_struct_field,
    STATE(99), 1,
      sym_comment,
  [1087] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(71), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(114), 1,
      sym_comment,
  [1106] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(43), 1,
      aux_sym_array_repeat1,
    STATE(119), 1,
      sym_comment,
  [1125] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(75), 1,
      sym_struct_field,
    STATE(100), 1,
      sym_comment,
  [1144] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(37), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(117), 1,
      sym_comment,
  [1163] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(78), 1,
      aux_sym_array_repeat1,
    STATE(118), 1,
      sym_comment,
  [1182] = 6,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(71), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(106), 1,
      sym_comment,
  [1201] = 5,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(121), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [1218] = 5,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_quoted_string,
    STATE(115), 1,
      sym_string,
    STATE(19), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [1235] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(75), 1,
      sym_struct_field,
    STATE(95), 1,
      sym_comment,
  [1254] = 4,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(126), 1,
      anon_sym_BSLASH,
    STATE(48), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1268] = 1,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1276] = 1,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1284] = 1,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1292] = 1,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1300] = 1,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1308] = 1,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1316] = 1,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1324] = 1,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1332] = 1,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1340] = 1,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1348] = 1,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1356] = 1,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1364] = 1,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1372] = 5,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    STATE(75), 1,
      sym_struct_field,
    STATE(102), 1,
      sym_comment,
  [1388] = 1,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1396] = 1,
    ACTIONS(155), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1404] = 4,
    ACTIONS(157), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(161), 1,
      anon_sym_BSLASH,
    STATE(48), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1418] = 1,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1426] = 1,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1434] = 1,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1442] = 1,
    ACTIONS(169), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1450] = 1,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1458] = 3,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_top_level_struct_repeat1,
    ACTIONS(173), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1470] = 4,
    ACTIONS(161), 1,
      anon_sym_BSLASH,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
    ACTIONS(180), 1,
      aux_sym_quoted_string_token1,
    STATE(65), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1484] = 1,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1492] = 3,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_map_repeat1,
    ACTIONS(187), 2,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1503] = 1,
    ACTIONS(173), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1510] = 1,
    ACTIONS(189), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1517] = 1,
    ACTIONS(191), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1524] = 3,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_array_repeat1,
    ACTIONS(196), 2,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1535] = 1,
    ACTIONS(198), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1541] = 3,
    ACTIONS(200), 1,
      anon_sym_LBRACE,
    ACTIONS(202), 1,
      aux_sym_struct_name_token2,
    STATE(80), 1,
      aux_sym_struct_name_repeat1,
  [1551] = 1,
    ACTIONS(205), 3,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
  [1557] = 1,
    ACTIONS(187), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1563] = 3,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
    ACTIONS(209), 1,
      aux_sym_tag_token2,
    STATE(91), 1,
      aux_sym_tag_repeat1,
  [1573] = 1,
    ACTIONS(211), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1579] = 1,
    ACTIONS(213), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1585] = 3,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
    ACTIONS(217), 1,
      aux_sym_struct_name_token2,
    STATE(89), 1,
      aux_sym_struct_name_repeat1,
  [1595] = 2,
    ACTIONS(221), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(219), 2,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
  [1603] = 1,
    ACTIONS(196), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1609] = 3,
    ACTIONS(223), 1,
      anon_sym_LBRACE,
    ACTIONS(225), 1,
      aux_sym_struct_name_token2,
    STATE(80), 1,
      aux_sym_struct_name_repeat1,
  [1619] = 3,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
    ACTIONS(229), 1,
      aux_sym_tag_token2,
    STATE(90), 1,
      aux_sym_tag_repeat1,
  [1629] = 3,
    ACTIONS(232), 1,
      anon_sym_LPAREN,
    ACTIONS(234), 1,
      aux_sym_tag_token2,
    STATE(90), 1,
      aux_sym_tag_repeat1,
  [1639] = 1,
    ACTIONS(236), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1645] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
  [1652] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
  [1659] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
  [1666] = 2,
    ACTIONS(242), 1,
      aux_sym_tag_token1,
    STATE(107), 1,
      sym_tag,
  [1673] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [1680] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
  [1687] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
  [1694] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
  [1701] = 1,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
  [1705] = 1,
    ACTIONS(71), 1,
      anon_sym_DOT,
  [1709] = 1,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
  [1713] = 1,
    ACTIONS(246), 1,
      anon_sym_LBRACE,
  [1717] = 1,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
  [1721] = 1,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
  [1725] = 1,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
  [1729] = 1,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
  [1733] = 1,
    ACTIONS(254), 1,
      anon_sym_EQ,
  [1737] = 1,
    ACTIONS(256), 1,
      anon_sym_EQ,
  [1741] = 1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [1745] = 1,
    ACTIONS(258), 1,
      anon_sym_COLON,
  [1749] = 1,
    ACTIONS(260), 1,
      aux_sym_line_string_token1,
  [1753] = 1,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
  [1757] = 1,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
  [1761] = 1,
    ACTIONS(264), 1,
      sym_identifier,
  [1765] = 1,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
  [1769] = 1,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
  [1773] = 1,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
  [1777] = 1,
    ACTIONS(266), 1,
      sym_identifier,
  [1781] = 1,
    ACTIONS(268), 1,
      anon_sym_COLON,
  [1785] = 1,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
  [1789] = 1,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 58,
  [SMALL_STATE(4)] = 116,
  [SMALL_STATE(5)] = 174,
  [SMALL_STATE(6)] = 229,
  [SMALL_STATE(7)] = 275,
  [SMALL_STATE(8)] = 321,
  [SMALL_STATE(9)] = 367,
  [SMALL_STATE(10)] = 410,
  [SMALL_STATE(11)] = 453,
  [SMALL_STATE(12)] = 496,
  [SMALL_STATE(13)] = 539,
  [SMALL_STATE(14)] = 582,
  [SMALL_STATE(15)] = 605,
  [SMALL_STATE(16)] = 628,
  [SMALL_STATE(17)] = 666,
  [SMALL_STATE(18)] = 698,
  [SMALL_STATE(19)] = 730,
  [SMALL_STATE(20)] = 747,
  [SMALL_STATE(21)] = 764,
  [SMALL_STATE(22)] = 793,
  [SMALL_STATE(23)] = 804,
  [SMALL_STATE(24)] = 827,
  [SMALL_STATE(25)] = 837,
  [SMALL_STATE(26)] = 847,
  [SMALL_STATE(27)] = 867,
  [SMALL_STATE(28)] = 877,
  [SMALL_STATE(29)] = 897,
  [SMALL_STATE(30)] = 916,
  [SMALL_STATE(31)] = 935,
  [SMALL_STATE(32)] = 954,
  [SMALL_STATE(33)] = 973,
  [SMALL_STATE(34)] = 992,
  [SMALL_STATE(35)] = 1011,
  [SMALL_STATE(36)] = 1030,
  [SMALL_STATE(37)] = 1049,
  [SMALL_STATE(38)] = 1068,
  [SMALL_STATE(39)] = 1087,
  [SMALL_STATE(40)] = 1106,
  [SMALL_STATE(41)] = 1125,
  [SMALL_STATE(42)] = 1144,
  [SMALL_STATE(43)] = 1163,
  [SMALL_STATE(44)] = 1182,
  [SMALL_STATE(45)] = 1201,
  [SMALL_STATE(46)] = 1218,
  [SMALL_STATE(47)] = 1235,
  [SMALL_STATE(48)] = 1254,
  [SMALL_STATE(49)] = 1268,
  [SMALL_STATE(50)] = 1276,
  [SMALL_STATE(51)] = 1284,
  [SMALL_STATE(52)] = 1292,
  [SMALL_STATE(53)] = 1300,
  [SMALL_STATE(54)] = 1308,
  [SMALL_STATE(55)] = 1316,
  [SMALL_STATE(56)] = 1324,
  [SMALL_STATE(57)] = 1332,
  [SMALL_STATE(58)] = 1340,
  [SMALL_STATE(59)] = 1348,
  [SMALL_STATE(60)] = 1356,
  [SMALL_STATE(61)] = 1364,
  [SMALL_STATE(62)] = 1372,
  [SMALL_STATE(63)] = 1388,
  [SMALL_STATE(64)] = 1396,
  [SMALL_STATE(65)] = 1404,
  [SMALL_STATE(66)] = 1418,
  [SMALL_STATE(67)] = 1426,
  [SMALL_STATE(68)] = 1434,
  [SMALL_STATE(69)] = 1442,
  [SMALL_STATE(70)] = 1450,
  [SMALL_STATE(71)] = 1458,
  [SMALL_STATE(72)] = 1470,
  [SMALL_STATE(73)] = 1484,
  [SMALL_STATE(74)] = 1492,
  [SMALL_STATE(75)] = 1503,
  [SMALL_STATE(76)] = 1510,
  [SMALL_STATE(77)] = 1517,
  [SMALL_STATE(78)] = 1524,
  [SMALL_STATE(79)] = 1535,
  [SMALL_STATE(80)] = 1541,
  [SMALL_STATE(81)] = 1551,
  [SMALL_STATE(82)] = 1557,
  [SMALL_STATE(83)] = 1563,
  [SMALL_STATE(84)] = 1573,
  [SMALL_STATE(85)] = 1579,
  [SMALL_STATE(86)] = 1585,
  [SMALL_STATE(87)] = 1595,
  [SMALL_STATE(88)] = 1603,
  [SMALL_STATE(89)] = 1609,
  [SMALL_STATE(90)] = 1619,
  [SMALL_STATE(91)] = 1629,
  [SMALL_STATE(92)] = 1639,
  [SMALL_STATE(93)] = 1645,
  [SMALL_STATE(94)] = 1652,
  [SMALL_STATE(95)] = 1659,
  [SMALL_STATE(96)] = 1666,
  [SMALL_STATE(97)] = 1673,
  [SMALL_STATE(98)] = 1680,
  [SMALL_STATE(99)] = 1687,
  [SMALL_STATE(100)] = 1694,
  [SMALL_STATE(101)] = 1701,
  [SMALL_STATE(102)] = 1705,
  [SMALL_STATE(103)] = 1709,
  [SMALL_STATE(104)] = 1713,
  [SMALL_STATE(105)] = 1717,
  [SMALL_STATE(106)] = 1721,
  [SMALL_STATE(107)] = 1725,
  [SMALL_STATE(108)] = 1729,
  [SMALL_STATE(109)] = 1733,
  [SMALL_STATE(110)] = 1737,
  [SMALL_STATE(111)] = 1741,
  [SMALL_STATE(112)] = 1745,
  [SMALL_STATE(113)] = 1749,
  [SMALL_STATE(114)] = 1753,
  [SMALL_STATE(115)] = 1757,
  [SMALL_STATE(116)] = 1761,
  [SMALL_STATE(117)] = 1765,
  [SMALL_STATE(118)] = 1769,
  [SMALL_STATE(119)] = 1773,
  [SMALL_STATE(120)] = 1777,
  [SMALL_STATE(121)] = 1781,
  [SMALL_STATE(122)] = 1785,
  [SMALL_STATE(123)] = 1789,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(14),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(113),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_string, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(48),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(81),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, .production_id = 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, .production_id = 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 6),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, .production_id = 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, .production_id = 1),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, .production_id = 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 5),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_string, 5, .production_id = 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_top_level_struct_repeat1, 2),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_top_level_struct_repeat1, 2), SHIFT_REPEAT(62),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(21),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 5, .production_id = 5),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, .production_id = 3),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(5),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_field, 4, .production_id = 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_name_repeat1, 2),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_name_repeat1, 2), SHIFT_REPEAT(80),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_elem, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_field, 3, .production_id = 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_name, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_name, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(90),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_elem, 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 4),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [252] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ziggy(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
