#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 6

enum ts_symbol_identifiers {
  anon_sym_COMMA = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  aux_sym_struct_name_token1 = 4,
  aux_sym_struct_name_token2 = 5,
  anon_sym_DOT = 6,
  anon_sym_EQ = 7,
  anon_sym_COLON = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_AT = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  aux_sym_tag_token1 = 14,
  aux_sym_tag_token2 = 15,
  anon_sym_BSLASH_BSLASH = 16,
  aux_sym_line_string_token1 = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_quoted_string_token1 = 19,
  anon_sym_BSLASH = 20,
  aux_sym_escape_sequence_token1 = 21,
  aux_sym_escape_sequence_token2 = 22,
  aux_sym_escape_sequence_token3 = 23,
  sym_identifier = 24,
  aux_sym_float_token1 = 25,
  aux_sym_float_token2 = 26,
  aux_sym_float_token3 = 27,
  aux_sym_float_token4 = 28,
  aux_sym_integer_token1 = 29,
  aux_sym_integer_token2 = 30,
  aux_sym_integer_token3 = 31,
  aux_sym_integer_token4 = 32,
  sym_true = 33,
  sym_false = 34,
  sym_null = 35,
  aux_sym_comment_token1 = 36,
  aux_sym_top_comment_token1 = 37,
  sym_document = 38,
  sym__value = 39,
  sym_top_level_struct = 40,
  sym_struct = 41,
  sym_struct_name = 42,
  sym_struct_field = 43,
  sym_map = 44,
  sym_map_field = 45,
  sym_array = 46,
  sym_array_elem = 47,
  sym_tag_string = 48,
  sym_tag = 49,
  sym_string = 50,
  sym_line_string = 51,
  sym_quoted_string = 52,
  sym_escape_sequence = 53,
  sym_float = 54,
  sym_integer = 55,
  sym_comment = 56,
  sym_top_comment = 57,
  aux_sym_top_level_struct_repeat1 = 58,
  aux_sym_struct_name_repeat1 = 59,
  aux_sym_map_repeat1 = 60,
  aux_sym_array_repeat1 = 61,
  aux_sym_tag_repeat1 = 62,
  aux_sym_string_repeat1 = 63,
  aux_sym_quoted_string_repeat1 = 64,
  aux_sym_comment_repeat1 = 65,
  aux_sym_top_comment_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_struct_name_token1] = "struct_name_token1",
  [aux_sym_struct_name_token2] = "struct_name_token2",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_tag_token1] = "tag_token1",
  [aux_sym_tag_token2] = "tag_token2",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [aux_sym_line_string_token1] = "line_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [aux_sym_escape_sequence_token2] = "escape_sequence_token2",
  [aux_sym_escape_sequence_token3] = "escape_sequence_token3",
  [sym_identifier] = "identifier",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [aux_sym_float_token3] = "float_token3",
  [aux_sym_float_token4] = "float_token4",
  [aux_sym_integer_token1] = "integer_token1",
  [aux_sym_integer_token2] = "integer_token2",
  [aux_sym_integer_token3] = "integer_token3",
  [aux_sym_integer_token4] = "integer_token4",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_top_comment_token1] = "top_comment_token1",
  [sym_document] = "document",
  [sym__value] = "_value",
  [sym_top_level_struct] = "top_level_struct",
  [sym_struct] = "struct",
  [sym_struct_name] = "struct_name",
  [sym_struct_field] = "struct_field",
  [sym_map] = "map",
  [sym_map_field] = "map_field",
  [sym_array] = "array",
  [sym_array_elem] = "array_elem",
  [sym_tag_string] = "tag_string",
  [sym_tag] = "tag",
  [sym_string] = "string",
  [sym_line_string] = "line_string",
  [sym_quoted_string] = "quoted_string",
  [sym_escape_sequence] = "escape_sequence",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [sym_comment] = "comment",
  [sym_top_comment] = "top_comment",
  [aux_sym_top_level_struct_repeat1] = "top_level_struct_repeat1",
  [aux_sym_struct_name_repeat1] = "struct_name_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_top_comment_repeat1] = "top_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_struct_name_token1] = aux_sym_struct_name_token1,
  [aux_sym_struct_name_token2] = aux_sym_struct_name_token2,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_tag_token1] = aux_sym_tag_token1,
  [aux_sym_tag_token2] = aux_sym_tag_token2,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [aux_sym_line_string_token1] = aux_sym_line_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [aux_sym_escape_sequence_token2] = aux_sym_escape_sequence_token2,
  [aux_sym_escape_sequence_token3] = aux_sym_escape_sequence_token3,
  [sym_identifier] = sym_identifier,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [aux_sym_float_token3] = aux_sym_float_token3,
  [aux_sym_float_token4] = aux_sym_float_token4,
  [aux_sym_integer_token1] = aux_sym_integer_token1,
  [aux_sym_integer_token2] = aux_sym_integer_token2,
  [aux_sym_integer_token3] = aux_sym_integer_token3,
  [aux_sym_integer_token4] = aux_sym_integer_token4,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_top_comment_token1] = aux_sym_top_comment_token1,
  [sym_document] = sym_document,
  [sym__value] = sym__value,
  [sym_top_level_struct] = sym_top_level_struct,
  [sym_struct] = sym_struct,
  [sym_struct_name] = sym_struct_name,
  [sym_struct_field] = sym_struct_field,
  [sym_map] = sym_map,
  [sym_map_field] = sym_map_field,
  [sym_array] = sym_array,
  [sym_array_elem] = sym_array_elem,
  [sym_tag_string] = sym_tag_string,
  [sym_tag] = sym_tag,
  [sym_string] = sym_string,
  [sym_line_string] = sym_line_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [sym_comment] = sym_comment,
  [sym_top_comment] = sym_top_comment,
  [aux_sym_top_level_struct_repeat1] = aux_sym_top_level_struct_repeat1,
  [aux_sym_struct_name_repeat1] = aux_sym_struct_name_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_top_comment_repeat1] = aux_sym_top_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_struct_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_name_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_top_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_top_level_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_name] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_map_field] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_array_elem] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_string] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_top_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_top_level_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_top_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_key, 0},
    {field_value, 2},
  [3] =
    {field_key, 1},
    {field_value, 3},
  [5] =
    {field_name, 1},
  [6] =
    {field_key, 2},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == ',') ADVANCE(42);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '=') ADVANCE(48);
      if (lookahead == '@') ADVANCE(52);
      if (lookahead == '[') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(63);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead == '}') ADVANCE(44);
      if (lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(83);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(1);
      END_STATE();
    case 5:
      if (lookahead == '0') ADVANCE(77);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 6:
      if (lookahead == '\\') ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(19);
      if (lookahead == 'x') ADVANCE(39);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(66);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16)
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == '{') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == '{') ADVANCE(37);
      END_STATE();
    case 20:
      if (lookahead == '}') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 22:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 23:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 24:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 25:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(74);
      END_STATE();
    case 26:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 27:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(75);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == ',') ADVANCE(42);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(77);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '@') ADVANCE(52);
      if (lookahead == '[') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'n') ADVANCE(17);
      if (lookahead == 't') ADVANCE(13);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_struct_name_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_struct_name_token2);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_tag_token1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_tag_token2);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_line_string_token1);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_line_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token3);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '_') ADVANCE(36);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '_') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_float_token3);
      if (lookahead == '_') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_float_token4);
      if (lookahead == '_') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (lookahead == '_') ADVANCE(25);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_integer_token2);
      if (lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_integer_token3);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_integer_token4);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '_') ADVANCE(29);
      if (lookahead == 'b') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(28);
      if (lookahead == 'x') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_integer_token4);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '_') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_top_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 40},
  [3] = {.lex_state = 40},
  [4] = {.lex_state = 40},
  [5] = {.lex_state = 40},
  [6] = {.lex_state = 40},
  [7] = {.lex_state = 40},
  [8] = {.lex_state = 40},
  [9] = {.lex_state = 40},
  [10] = {.lex_state = 40},
  [11] = {.lex_state = 40},
  [12] = {.lex_state = 40},
  [13] = {.lex_state = 40},
  [14] = {.lex_state = 40},
  [15] = {.lex_state = 40},
  [16] = {.lex_state = 40},
  [17] = {.lex_state = 40},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 40},
  [20] = {.lex_state = 40},
  [21] = {.lex_state = 40},
  [22] = {.lex_state = 40},
  [23] = {.lex_state = 40},
  [24] = {.lex_state = 40},
  [25] = {.lex_state = 40},
  [26] = {.lex_state = 40},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 40},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 40},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 40},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 16},
  [85] = {.lex_state = 18},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 18},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 18},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 40},
  [101] = {.lex_state = 26},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 27},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 58},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 27},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_struct_name_token1] = ACTIONS(1),
    [aux_sym_struct_name_token2] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_tag_token1] = ACTIONS(1),
    [aux_sym_tag_token2] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_escape_sequence_token3] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [aux_sym_top_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(125),
    [sym__value] = STATE(124),
    [sym_top_level_struct] = STATE(124),
    [sym_struct] = STATE(124),
    [sym_struct_name] = STATE(123),
    [sym_struct_field] = STATE(33),
    [sym_map] = STATE(124),
    [sym_array] = STATE(124),
    [sym_tag_string] = STATE(124),
    [sym_string] = STATE(124),
    [sym_line_string] = STATE(24),
    [sym_quoted_string] = STATE(41),
    [sym_float] = STATE(124),
    [sym_integer] = STATE(124),
    [sym_comment] = STATE(122),
    [sym_top_comment] = STATE(2),
    [aux_sym_string_repeat1] = STATE(24),
    [aux_sym_comment_repeat1] = STATE(16),
    [aux_sym_top_comment_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(25),
    [sym_false] = ACTIONS(25),
    [sym_null] = ACTIONS(25),
    [aux_sym_comment_token1] = ACTIONS(27),
    [aux_sym_top_comment_token1] = ACTIONS(29),
  },
  [2] = {
    [sym__value] = STATE(110),
    [sym_top_level_struct] = STATE(110),
    [sym_struct] = STATE(110),
    [sym_struct_name] = STATE(123),
    [sym_struct_field] = STATE(33),
    [sym_map] = STATE(110),
    [sym_array] = STATE(110),
    [sym_tag_string] = STATE(110),
    [sym_string] = STATE(110),
    [sym_line_string] = STATE(24),
    [sym_quoted_string] = STATE(41),
    [sym_float] = STATE(110),
    [sym_integer] = STATE(110),
    [sym_comment] = STATE(122),
    [aux_sym_string_repeat1] = STATE(24),
    [aux_sym_comment_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
    [sym_null] = ACTIONS(33),
    [aux_sym_comment_token1] = ACTIONS(27),
  },
  [3] = {
    [sym__value] = STATE(96),
    [sym_struct] = STATE(96),
    [sym_struct_name] = STATE(123),
    [sym_map] = STATE(96),
    [sym_array] = STATE(96),
    [sym_array_elem] = STATE(93),
    [sym_tag_string] = STATE(96),
    [sym_string] = STATE(96),
    [sym_line_string] = STATE(24),
    [sym_quoted_string] = STATE(41),
    [sym_float] = STATE(96),
    [sym_integer] = STATE(96),
    [sym_comment] = STATE(7),
    [aux_sym_string_repeat1] = STATE(24),
    [aux_sym_comment_repeat1] = STATE(16),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(37),
    [sym_false] = ACTIONS(37),
    [sym_null] = ACTIONS(37),
    [aux_sym_comment_token1] = ACTIONS(27),
  },
  [4] = {
    [sym__value] = STATE(96),
    [sym_struct] = STATE(96),
    [sym_struct_name] = STATE(123),
    [sym_map] = STATE(96),
    [sym_array] = STATE(96),
    [sym_array_elem] = STATE(40),
    [sym_tag_string] = STATE(96),
    [sym_string] = STATE(96),
    [sym_line_string] = STATE(24),
    [sym_quoted_string] = STATE(41),
    [sym_float] = STATE(96),
    [sym_integer] = STATE(96),
    [sym_comment] = STATE(9),
    [aux_sym_string_repeat1] = STATE(24),
    [aux_sym_comment_repeat1] = STATE(16),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(37),
    [sym_false] = ACTIONS(37),
    [sym_null] = ACTIONS(37),
    [aux_sym_comment_token1] = ACTIONS(27),
  },
  [5] = {
    [sym__value] = STATE(96),
    [sym_struct] = STATE(96),
    [sym_struct_name] = STATE(123),
    [sym_map] = STATE(96),
    [sym_array] = STATE(96),
    [sym_array_elem] = STATE(93),
    [sym_tag_string] = STATE(96),
    [sym_string] = STATE(96),
    [sym_line_string] = STATE(24),
    [sym_quoted_string] = STATE(41),
    [sym_float] = STATE(96),
    [sym_integer] = STATE(96),
    [sym_comment] = STATE(8),
    [aux_sym_string_repeat1] = STATE(24),
    [aux_sym_comment_repeat1] = STATE(16),
    [anon_sym_LBRACE] = ACTIONS(5),
    [aux_sym_struct_name_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [aux_sym_float_token2] = ACTIONS(19),
    [aux_sym_float_token3] = ACTIONS(19),
    [aux_sym_float_token4] = ACTIONS(19),
    [aux_sym_integer_token1] = ACTIONS(21),
    [aux_sym_integer_token2] = ACTIONS(21),
    [aux_sym_integer_token3] = ACTIONS(23),
    [aux_sym_integer_token4] = ACTIONS(23),
    [sym_true] = ACTIONS(37),
    [sym_false] = ACTIONS(37),
    [sym_null] = ACTIONS(37),
    [aux_sym_comment_token1] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    STATE(11), 1,
      sym_comment,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(41), 1,
      sym_quoted_string,
    STATE(93), 1,
      sym_array_elem,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(37), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(96), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [70] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      sym_quoted_string,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(43), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(87), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [131] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      sym_quoted_string,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(43), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(87), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [192] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      sym_quoted_string,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(43), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(87), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [253] = 14,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_quoted_string,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(49), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(86), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [311] = 14,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_quoted_string,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(43), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(87), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [369] = 14,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_quoted_string,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(51), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(80), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [427] = 14,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_quoted_string,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(53), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(89), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [485] = 14,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      aux_sym_struct_name_token1,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_quoted_string,
    STATE(123), 1,
      sym_struct_name,
    ACTIONS(21), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
    ACTIONS(23), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(55), 3,
      sym_true,
      sym_false,
      sym_null,
    ACTIONS(19), 4,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
    STATE(82), 8,
      sym__value,
      sym_struct,
      sym_map,
      sym_array,
      sym_tag_string,
      sym_string,
      sym_float,
      sym_integer,
  [543] = 4,
    ACTIONS(61), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    ACTIONS(59), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    ACTIONS(57), 19,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
      sym_true,
      sym_false,
      sym_null,
  [575] = 4,
    ACTIONS(68), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      aux_sym_comment_repeat1,
    ACTIONS(66), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    ACTIONS(64), 19,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
      sym_true,
      sym_false,
      sym_null,
  [607] = 4,
    ACTIONS(74), 1,
      aux_sym_top_comment_token1,
    STATE(18), 1,
      aux_sym_top_comment_repeat1,
    ACTIONS(72), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    ACTIONS(70), 18,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
      sym_true,
      sym_false,
      sym_null,
      aux_sym_comment_token1,
  [638] = 4,
    ACTIONS(80), 1,
      aux_sym_top_comment_token1,
    STATE(18), 1,
      aux_sym_top_comment_repeat1,
    ACTIONS(78), 2,
      aux_sym_integer_token3,
      aux_sym_integer_token4,
    ACTIONS(76), 18,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      aux_sym_struct_name_token1,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_AT,
      anon_sym_BSLASH_BSLASH,
      anon_sym_DQUOTE,
      aux_sym_float_token1,
      aux_sym_float_token2,
      aux_sym_float_token3,
      aux_sym_float_token4,
      aux_sym_integer_token1,
      aux_sym_integer_token2,
      sym_true,
      sym_false,
      sym_null,
      aux_sym_comment_token1,
  [669] = 12,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(25), 1,
      sym_comment,
    STATE(34), 1,
      sym_struct_field,
    STATE(35), 1,
      sym_map_field,
    STATE(41), 1,
      sym_quoted_string,
    STATE(121), 1,
      sym_string,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [707] = 10,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(30), 1,
      sym_comment,
    STATE(41), 1,
      sym_quoted_string,
    STATE(91), 1,
      sym_map_field,
    STATE(121), 1,
      sym_string,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [739] = 10,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(26), 1,
      sym_comment,
    STATE(41), 1,
      sym_quoted_string,
    STATE(91), 1,
      sym_map_field,
    STATE(121), 1,
      sym_string,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [771] = 9,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(32), 1,
      sym_comment,
    STATE(41), 1,
      sym_quoted_string,
    STATE(91), 1,
      sym_map_field,
    STATE(121), 1,
      sym_string,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [800] = 3,
    ACTIONS(91), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [816] = 3,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(23), 2,
      sym_line_string,
      aux_sym_string_repeat1,
    ACTIONS(94), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [832] = 7,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(98), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_quoted_string,
    STATE(106), 1,
      sym_string,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [855] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_quoted_string,
    STATE(106), 1,
      sym_string,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [875] = 1,
    ACTIONS(100), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [885] = 1,
    ACTIONS(102), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_BSLASH_BSLASH,
      aux_sym_comment_token1,
  [895] = 1,
    ACTIONS(104), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      aux_sym_comment_token1,
  [905] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_quoted_string,
    STATE(106), 1,
      sym_string,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [925] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(72), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(119), 1,
      sym_comment,
  [944] = 5,
    ACTIONS(15), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_quoted_string,
    STATE(106), 1,
      sym_string,
    STATE(24), 2,
      sym_line_string,
      aux_sym_string_repeat1,
  [961] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(45), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(113), 1,
      sym_comment,
  [980] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(31), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(109), 1,
      sym_comment,
  [999] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(49), 1,
      aux_sym_map_repeat1,
    STATE(117), 1,
      sym_comment,
  [1018] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(79), 1,
      sym_struct_field,
    STATE(105), 1,
      sym_comment,
  [1037] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(79), 1,
      sym_struct_field,
    STATE(103), 1,
      sym_comment,
  [1056] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(79), 1,
      sym_struct_field,
    STATE(104), 1,
      sym_comment,
  [1075] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(48), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(114), 1,
      sym_comment,
  [1094] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(46), 1,
      aux_sym_array_repeat1,
    STATE(112), 1,
      sym_comment,
  [1113] = 1,
    ACTIONS(94), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1122] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(79), 1,
      sym_struct_field,
    STATE(97), 1,
      sym_comment,
  [1141] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(39), 1,
      sym_struct_field,
    STATE(102), 1,
      sym_comment,
  [1160] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(79), 1,
      sym_struct_field,
    STATE(98), 1,
      sym_comment,
  [1179] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(72), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(108), 1,
      sym_comment,
  [1198] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(81), 1,
      aux_sym_array_repeat1,
    STATE(118), 1,
      sym_comment,
  [1217] = 6,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(79), 1,
      sym_struct_field,
    STATE(99), 1,
      sym_comment,
  [1236] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(72), 1,
      aux_sym_top_level_struct_repeat1,
    STATE(120), 1,
      sym_comment,
  [1255] = 6,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(78), 1,
      aux_sym_map_repeat1,
    STATE(128), 1,
      sym_comment,
  [1274] = 1,
    ACTIONS(150), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1282] = 4,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(157), 1,
      anon_sym_BSLASH,
    STATE(51), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1296] = 1,
    ACTIONS(160), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1304] = 1,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1312] = 1,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1320] = 1,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1328] = 1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1336] = 5,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      aux_sym_comment_token1,
    STATE(16), 1,
      aux_sym_comment_repeat1,
    STATE(79), 1,
      sym_struct_field,
    STATE(122), 1,
      sym_comment,
  [1352] = 1,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1360] = 4,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
    ACTIONS(174), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(176), 1,
      anon_sym_BSLASH,
    STATE(66), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1374] = 1,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1382] = 1,
    ACTIONS(180), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1390] = 1,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1398] = 1,
    ACTIONS(150), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1406] = 1,
    ACTIONS(184), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1414] = 1,
    ACTIONS(186), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1422] = 4,
    ACTIONS(176), 1,
      anon_sym_BSLASH,
    ACTIONS(188), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 1,
      aux_sym_quoted_string_token1,
    STATE(51), 2,
      sym_escape_sequence,
      aux_sym_quoted_string_repeat1,
  [1436] = 1,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1444] = 1,
    ACTIONS(194), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1452] = 1,
    ACTIONS(196), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1460] = 1,
    ACTIONS(198), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1468] = 1,
    ACTIONS(200), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1476] = 3,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_top_level_struct_repeat1,
    ACTIONS(202), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1488] = 1,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1496] = 1,
    ACTIONS(209), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1504] = 1,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1512] = 1,
    ACTIONS(213), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1520] = 1,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1528] = 3,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_map_repeat1,
    ACTIONS(220), 2,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1539] = 1,
    ACTIONS(202), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1546] = 1,
    ACTIONS(222), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1553] = 3,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym_array_repeat1,
    ACTIONS(227), 2,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1564] = 1,
    ACTIONS(229), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1571] = 3,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    ACTIONS(233), 1,
      aux_sym_tag_token2,
    STATE(90), 1,
      aux_sym_tag_repeat1,
  [1581] = 1,
    ACTIONS(235), 3,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
      aux_sym_escape_sequence_token3,
  [1587] = 3,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
    ACTIONS(239), 1,
      aux_sym_struct_name_token2,
    STATE(85), 1,
      aux_sym_struct_name_repeat1,
  [1597] = 1,
    ACTIONS(242), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1603] = 1,
    ACTIONS(244), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1609] = 3,
    ACTIONS(246), 1,
      anon_sym_LBRACE,
    ACTIONS(248), 1,
      aux_sym_struct_name_token2,
    STATE(85), 1,
      aux_sym_struct_name_repeat1,
  [1619] = 1,
    ACTIONS(250), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1625] = 3,
    ACTIONS(252), 1,
      anon_sym_LPAREN,
    ACTIONS(254), 1,
      aux_sym_tag_token2,
    STATE(92), 1,
      aux_sym_tag_repeat1,
  [1635] = 1,
    ACTIONS(220), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_comment_token1,
  [1641] = 3,
    ACTIONS(256), 1,
      anon_sym_LPAREN,
    ACTIONS(258), 1,
      aux_sym_tag_token2,
    STATE(92), 1,
      aux_sym_tag_repeat1,
  [1651] = 1,
    ACTIONS(227), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1657] = 3,
    ACTIONS(261), 1,
      anon_sym_LBRACE,
    ACTIONS(263), 1,
      aux_sym_struct_name_token2,
    STATE(88), 1,
      aux_sym_struct_name_repeat1,
  [1667] = 2,
    ACTIONS(267), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(265), 2,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
  [1675] = 1,
    ACTIONS(269), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_comment_token1,
  [1681] = 2,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
  [1688] = 2,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
  [1695] = 2,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
  [1702] = 2,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(116), 1,
      sym_quoted_string,
  [1709] = 2,
    ACTIONS(271), 1,
      aux_sym_tag_token1,
    STATE(115), 1,
      sym_tag,
  [1716] = 2,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
  [1723] = 2,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_RBRACE,
  [1730] = 2,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
  [1737] = 2,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
  [1744] = 1,
    ACTIONS(279), 1,
      anon_sym_COLON,
  [1748] = 1,
    ACTIONS(281), 1,
      anon_sym_EQ,
  [1752] = 1,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
  [1756] = 1,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
  [1760] = 1,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
  [1764] = 1,
    ACTIONS(285), 1,
      sym_identifier,
  [1768] = 1,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
  [1772] = 1,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
  [1776] = 1,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
  [1780] = 1,
    ACTIONS(287), 1,
      anon_sym_LPAREN,
  [1784] = 1,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [1788] = 1,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
  [1792] = 1,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
  [1796] = 1,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
  [1800] = 1,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
  [1804] = 1,
    ACTIONS(291), 1,
      anon_sym_COLON,
  [1808] = 1,
    ACTIONS(98), 1,
      anon_sym_DOT,
  [1812] = 1,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
  [1816] = 1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
  [1820] = 1,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
  [1824] = 1,
    ACTIONS(297), 1,
      aux_sym_line_string_token1,
  [1828] = 1,
    ACTIONS(299), 1,
      anon_sym_EQ,
  [1832] = 1,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
  [1836] = 1,
    ACTIONS(301), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 70,
  [SMALL_STATE(8)] = 131,
  [SMALL_STATE(9)] = 192,
  [SMALL_STATE(10)] = 253,
  [SMALL_STATE(11)] = 311,
  [SMALL_STATE(12)] = 369,
  [SMALL_STATE(13)] = 427,
  [SMALL_STATE(14)] = 485,
  [SMALL_STATE(15)] = 543,
  [SMALL_STATE(16)] = 575,
  [SMALL_STATE(17)] = 607,
  [SMALL_STATE(18)] = 638,
  [SMALL_STATE(19)] = 669,
  [SMALL_STATE(20)] = 707,
  [SMALL_STATE(21)] = 739,
  [SMALL_STATE(22)] = 771,
  [SMALL_STATE(23)] = 800,
  [SMALL_STATE(24)] = 816,
  [SMALL_STATE(25)] = 832,
  [SMALL_STATE(26)] = 855,
  [SMALL_STATE(27)] = 875,
  [SMALL_STATE(28)] = 885,
  [SMALL_STATE(29)] = 895,
  [SMALL_STATE(30)] = 905,
  [SMALL_STATE(31)] = 925,
  [SMALL_STATE(32)] = 944,
  [SMALL_STATE(33)] = 961,
  [SMALL_STATE(34)] = 980,
  [SMALL_STATE(35)] = 999,
  [SMALL_STATE(36)] = 1018,
  [SMALL_STATE(37)] = 1037,
  [SMALL_STATE(38)] = 1056,
  [SMALL_STATE(39)] = 1075,
  [SMALL_STATE(40)] = 1094,
  [SMALL_STATE(41)] = 1113,
  [SMALL_STATE(42)] = 1122,
  [SMALL_STATE(43)] = 1141,
  [SMALL_STATE(44)] = 1160,
  [SMALL_STATE(45)] = 1179,
  [SMALL_STATE(46)] = 1198,
  [SMALL_STATE(47)] = 1217,
  [SMALL_STATE(48)] = 1236,
  [SMALL_STATE(49)] = 1255,
  [SMALL_STATE(50)] = 1274,
  [SMALL_STATE(51)] = 1282,
  [SMALL_STATE(52)] = 1296,
  [SMALL_STATE(53)] = 1304,
  [SMALL_STATE(54)] = 1312,
  [SMALL_STATE(55)] = 1320,
  [SMALL_STATE(56)] = 1328,
  [SMALL_STATE(57)] = 1336,
  [SMALL_STATE(58)] = 1352,
  [SMALL_STATE(59)] = 1360,
  [SMALL_STATE(60)] = 1374,
  [SMALL_STATE(61)] = 1382,
  [SMALL_STATE(62)] = 1390,
  [SMALL_STATE(63)] = 1398,
  [SMALL_STATE(64)] = 1406,
  [SMALL_STATE(65)] = 1414,
  [SMALL_STATE(66)] = 1422,
  [SMALL_STATE(67)] = 1436,
  [SMALL_STATE(68)] = 1444,
  [SMALL_STATE(69)] = 1452,
  [SMALL_STATE(70)] = 1460,
  [SMALL_STATE(71)] = 1468,
  [SMALL_STATE(72)] = 1476,
  [SMALL_STATE(73)] = 1488,
  [SMALL_STATE(74)] = 1496,
  [SMALL_STATE(75)] = 1504,
  [SMALL_STATE(76)] = 1512,
  [SMALL_STATE(77)] = 1520,
  [SMALL_STATE(78)] = 1528,
  [SMALL_STATE(79)] = 1539,
  [SMALL_STATE(80)] = 1546,
  [SMALL_STATE(81)] = 1553,
  [SMALL_STATE(82)] = 1564,
  [SMALL_STATE(83)] = 1571,
  [SMALL_STATE(84)] = 1581,
  [SMALL_STATE(85)] = 1587,
  [SMALL_STATE(86)] = 1597,
  [SMALL_STATE(87)] = 1603,
  [SMALL_STATE(88)] = 1609,
  [SMALL_STATE(89)] = 1619,
  [SMALL_STATE(90)] = 1625,
  [SMALL_STATE(91)] = 1635,
  [SMALL_STATE(92)] = 1641,
  [SMALL_STATE(93)] = 1651,
  [SMALL_STATE(94)] = 1657,
  [SMALL_STATE(95)] = 1667,
  [SMALL_STATE(96)] = 1675,
  [SMALL_STATE(97)] = 1681,
  [SMALL_STATE(98)] = 1688,
  [SMALL_STATE(99)] = 1695,
  [SMALL_STATE(100)] = 1702,
  [SMALL_STATE(101)] = 1709,
  [SMALL_STATE(102)] = 1716,
  [SMALL_STATE(103)] = 1723,
  [SMALL_STATE(104)] = 1730,
  [SMALL_STATE(105)] = 1737,
  [SMALL_STATE(106)] = 1744,
  [SMALL_STATE(107)] = 1748,
  [SMALL_STATE(108)] = 1752,
  [SMALL_STATE(109)] = 1756,
  [SMALL_STATE(110)] = 1760,
  [SMALL_STATE(111)] = 1764,
  [SMALL_STATE(112)] = 1768,
  [SMALL_STATE(113)] = 1772,
  [SMALL_STATE(114)] = 1776,
  [SMALL_STATE(115)] = 1780,
  [SMALL_STATE(116)] = 1784,
  [SMALL_STATE(117)] = 1788,
  [SMALL_STATE(118)] = 1792,
  [SMALL_STATE(119)] = 1796,
  [SMALL_STATE(120)] = 1800,
  [SMALL_STATE(121)] = 1804,
  [SMALL_STATE(122)] = 1808,
  [SMALL_STATE(123)] = 1812,
  [SMALL_STATE(124)] = 1816,
  [SMALL_STATE(125)] = 1820,
  [SMALL_STATE(126)] = 1824,
  [SMALL_STATE(127)] = 1828,
  [SMALL_STATE(128)] = 1832,
  [SMALL_STATE(129)] = 1836,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(15),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_comment, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_top_comment, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_top_comment_repeat1, 2),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_top_comment_repeat1, 2),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_top_comment_repeat1, 2), SHIFT_REPEAT(18),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(126),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_string, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(51),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2), SHIFT_REPEAT(84),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 6),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, .production_id = 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 2),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 6),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, .production_id = 1),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 5),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, .production_id = 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, .production_id = 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_top_level_struct_repeat1, 2),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_top_level_struct_repeat1, 2), SHIFT_REPEAT(57),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_string, 5, .production_id = 4),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, .production_id = 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2), SHIFT_REPEAT(22),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, .production_id = 3),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(6),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 5, .production_id = 5),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_name_repeat1, 2),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_name_repeat1, 2), SHIFT_REPEAT(85),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_field, 4, .production_id = 3),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_elem, 2),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_name, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_field, 3, .production_id = 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2),
  [258] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(92),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_name, 1),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 2),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_elem, 1),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_struct, 4),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [295] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ziggy(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
