#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 13

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_DOLLAR = 2,
  anon_sym_EQ = 3,
  anon_sym_LBRACK_RBRACK = 4,
  anon_sym_LBRACE_COLON_RBRACE = 5,
  anon_sym_QMARK = 6,
  anon_sym_bytes = 7,
  anon_sym_int = 8,
  anon_sym_float = 9,
  anon_sym_bool = 10,
  anon_sym_any = 11,
  anon_sym_null = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  anon_sym_LBRACE_RBRACE = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_string_token1 = 17,
  sym_number = 18,
  anon_sym_AT = 19,
  anon_sym_struct = 20,
  anon_sym_LBRACE = 21,
  anon_sym_COMMA = 22,
  anon_sym_RBRACE = 23,
  anon_sym_union = 24,
  anon_sym_COLON = 25,
  aux_sym_doc_comment_token1 = 26,
  sym_schema = 27,
  sym_expr = 28,
  sym_default = 29,
  sym_string = 30,
  sym_struct = 31,
  sym_union = 32,
  sym_struct_field = 33,
  sym_union_field = 34,
  sym_doc_comment = 35,
  aux_sym_schema_repeat1 = 36,
  aux_sym_expr_repeat1 = 37,
  aux_sym_struct_repeat1 = 38,
  aux_sym_union_repeat1 = 39,
  aux_sym_doc_comment_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LBRACE_COLON_RBRACE] = "{:}",
  [anon_sym_QMARK] = "\?",
  [anon_sym_bytes] = "bytes",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_bool] = "bool",
  [anon_sym_any] = "any",
  [anon_sym_null] = "null",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_number] = "number",
  [anon_sym_AT] = "@",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_union] = "union",
  [anon_sym_COLON] = ":",
  [aux_sym_doc_comment_token1] = "doc_comment_token1",
  [sym_schema] = "schema",
  [sym_expr] = "expr",
  [sym_default] = "default",
  [sym_string] = "string",
  [sym_struct] = "struct",
  [sym_union] = "union",
  [sym_struct_field] = "struct_field",
  [sym_union_field] = "union_field",
  [sym_doc_comment] = "doc_comment",
  [aux_sym_schema_repeat1] = "schema_repeat1",
  [aux_sym_expr_repeat1] = "expr_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_union_repeat1] = "union_repeat1",
  [aux_sym_doc_comment_repeat1] = "doc_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LBRACE_COLON_RBRACE] = anon_sym_LBRACE_COLON_RBRACE,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_bytes] = anon_sym_bytes,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_any] = anon_sym_any,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_number] = sym_number,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_union] = anon_sym_union,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_doc_comment_token1] = aux_sym_doc_comment_token1,
  [sym_schema] = sym_schema,
  [sym_expr] = sym_expr,
  [sym_default] = sym_default,
  [sym_string] = sym_string,
  [sym_struct] = sym_struct,
  [sym_union] = sym_union,
  [sym_struct_field] = sym_struct_field,
  [sym_union_field] = sym_union_field,
  [sym_doc_comment] = sym_doc_comment,
  [aux_sym_schema_repeat1] = aux_sym_schema_repeat1,
  [aux_sym_expr_repeat1] = aux_sym_expr_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_union_repeat1] = aux_sym_union_repeat1,
  [aux_sym_doc_comment_repeat1] = aux_sym_doc_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_COLON_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bytes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_any] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_union] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doc_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_default] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_union] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_union_field] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_schema_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_doc_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_default = 1,
  field_docs = 2,
  field_key = 3,
  field_name = 4,
  field_root = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_default] = "default",
  [field_docs] = "docs",
  [field_key] = "key",
  [field_name] = "name",
  [field_root] = "root",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 3},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 4},
  [11] = {.index = 20, .length = 4},
  [12] = {.index = 24, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_root, 2},
  [1] =
    {field_root, 3},
  [2] =
    {field_name, 1},
  [3] =
    {field_key, 0},
  [4] =
    {field_docs, 0},
    {field_key, 1},
  [6] =
    {field_docs, 0},
    {field_name, 2},
  [8] =
    {field_key, 0},
    {field_value, 2},
  [10] =
    {field_default, 1},
    {field_default, 2},
    {field_key, 0},
  [13] =
    {field_docs, 0},
    {field_key, 1},
    {field_value, 3},
  [16] =
    {field_default, 2},
    {field_default, 3},
    {field_docs, 0},
    {field_key, 1},
  [20] =
    {field_default, 3},
    {field_default, 4},
    {field_key, 0},
    {field_value, 2},
  [24] =
    {field_default, 4},
    {field_default, 5},
    {field_docs, 0},
    {field_key, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '"') ADVANCE(15);
      if (lookahead == '$') ADVANCE(9);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(25);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '?') ADVANCE(13);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(15);
      if (lookahead == '?') ADVANCE(13);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == '{') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == '}') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == '{') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6)
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(12);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE_COLON_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == ':') ADVANCE(7);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_doc_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'b') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == 'u') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == 'y') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_any);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_bytes);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_union);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 6},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 6},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 6},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 6},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 16},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE_COLON_RBRACE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_bytes] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_any] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_union] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_doc_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_schema] = STATE(117),
    [sym_doc_comment] = STATE(115),
    [aux_sym_doc_comment_repeat1] = STATE(67),
    [anon_sym_DOLLAR] = ACTIONS(3),
    [aux_sym_doc_comment_token1] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 1,
      anon_sym_union,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(74), 1,
      sym_union_field,
    STATE(102), 1,
      sym_doc_comment,
    STATE(46), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [30] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(17), 1,
      anon_sym_COMMA,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_union,
    STATE(24), 1,
      aux_sym_union_repeat1,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(36), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [60] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      aux_sym_struct_repeat1,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(33), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [90] = 4,
    STATE(30), 1,
      aux_sym_expr_repeat1,
    STATE(61), 1,
      sym_expr,
    ACTIONS(29), 3,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_COLON_RBRACE,
      anon_sym_QMARK,
    ACTIONS(27), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      sym_identifier,
  [110] = 4,
    STATE(30), 1,
      aux_sym_expr_repeat1,
    STATE(50), 1,
      sym_expr,
    ACTIONS(29), 3,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_COLON_RBRACE,
      anon_sym_QMARK,
    ACTIONS(27), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      sym_identifier,
  [130] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(31), 1,
      anon_sym_COMMA,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_struct_repeat1,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(49), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [160] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(68), 1,
      aux_sym_union_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(51), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [190] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(74), 1,
      sym_union_field,
    STATE(102), 1,
      sym_doc_comment,
    STATE(51), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [220] = 4,
    STATE(30), 1,
      aux_sym_expr_repeat1,
    STATE(62), 1,
      sym_expr,
    ACTIONS(29), 3,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_COLON_RBRACE,
      anon_sym_QMARK,
    ACTIONS(27), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      sym_identifier,
  [240] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(74), 1,
      sym_union_field,
    STATE(102), 1,
      sym_doc_comment,
    STATE(55), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [270] = 4,
    STATE(30), 1,
      aux_sym_expr_repeat1,
    STATE(42), 1,
      sym_expr,
    ACTIONS(29), 3,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_COLON_RBRACE,
      anon_sym_QMARK,
    ACTIONS(27), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      sym_identifier,
  [290] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(89), 1,
      sym_struct_field,
    STATE(101), 1,
      sym_doc_comment,
    STATE(43), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [320] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(74), 1,
      sym_union_field,
    STATE(102), 1,
      sym_doc_comment,
    STATE(31), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [350] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(47), 1,
      anon_sym_COMMA,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_struct_repeat1,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(47), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [380] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(89), 1,
      sym_struct_field,
    STATE(101), 1,
      sym_doc_comment,
    STATE(40), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [410] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(53), 1,
      anon_sym_COMMA,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_struct_repeat1,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(45), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [440] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(89), 1,
      sym_struct_field,
    STATE(101), 1,
      sym_doc_comment,
    STATE(47), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [470] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_union_field,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(102), 1,
      sym_doc_comment,
    STATE(35), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [500] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      sym_struct_field,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(101), 1,
      sym_doc_comment,
    STATE(54), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [530] = 4,
    STATE(30), 1,
      aux_sym_expr_repeat1,
    STATE(64), 1,
      sym_expr,
    ACTIONS(29), 3,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_COLON_RBRACE,
      anon_sym_QMARK,
    ACTIONS(27), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      sym_identifier,
  [550] = 4,
    STATE(30), 1,
      aux_sym_expr_repeat1,
    STATE(65), 1,
      sym_expr,
    ACTIONS(29), 3,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_COLON_RBRACE,
      anon_sym_QMARK,
    ACTIONS(27), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      sym_identifier,
  [570] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      aux_sym_union_repeat1,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(52), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [600] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(68), 1,
      aux_sym_union_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(55), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [630] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      sym_identifier,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(89), 1,
      sym_struct_field,
    STATE(101), 1,
      sym_doc_comment,
    STATE(49), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [660] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      sym_struct_field,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(101), 1,
      sym_doc_comment,
    STATE(34), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [690] = 9,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      sym_union_field,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(102), 1,
      sym_doc_comment,
    STATE(39), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [720] = 7,
    ACTIONS(73), 1,
      anon_sym_struct,
    ACTIONS(76), 1,
      anon_sym_union,
    ACTIONS(79), 1,
      aux_sym_doc_comment_token1,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [745] = 3,
    STATE(29), 1,
      aux_sym_expr_repeat1,
    ACTIONS(84), 3,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_COLON_RBRACE,
      anon_sym_QMARK,
    ACTIONS(82), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      sym_identifier,
  [762] = 3,
    STATE(29), 1,
      aux_sym_expr_repeat1,
    ACTIONS(89), 3,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_COLON_RBRACE,
      anon_sym_QMARK,
    ACTIONS(87), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      sym_identifier,
  [779] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [803] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [827] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [851] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [875] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_union,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [899] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [923] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [947] = 4,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    STATE(86), 1,
      sym_string,
    STATE(98), 1,
      sym_default,
    ACTIONS(97), 6,
      anon_sym_LBRACK_RBRACK,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACE_RBRACE,
      sym_number,
  [965] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [989] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1013] = 4,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    STATE(86), 1,
      sym_string,
    STATE(92), 1,
      sym_default,
    ACTIONS(97), 6,
      anon_sym_LBRACK_RBRACK,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACE_RBRACE,
      sym_number,
  [1031] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(37), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1055] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1079] = 4,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    STATE(86), 1,
      sym_string,
    STATE(95), 1,
      sym_default,
    ACTIONS(97), 6,
      anon_sym_LBRACK_RBRACK,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACE_RBRACE,
      sym_number,
  [1097] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1121] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1145] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1169] = 4,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    STATE(72), 1,
      sym_default,
    STATE(86), 1,
      sym_string,
    ACTIONS(97), 6,
      anon_sym_LBRACK_RBRACK,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACE_RBRACE,
      sym_number,
  [1187] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1211] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(32), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1235] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1259] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1283] = 4,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    STATE(77), 1,
      sym_default,
    STATE(86), 1,
      sym_string,
    ACTIONS(97), 6,
      anon_sym_LBRACK_RBRACK,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACE_RBRACE,
      sym_number,
  [1301] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1325] = 7,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(21), 1,
      anon_sym_union,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(103), 1,
      sym_doc_comment,
    STATE(28), 3,
      sym_struct,
      sym_union,
      aux_sym_schema_repeat1,
  [1349] = 4,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    STATE(85), 1,
      sym_default,
    STATE(86), 1,
      sym_string,
    ACTIONS(97), 6,
      anon_sym_LBRACK_RBRACK,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACE_RBRACE,
      sym_number,
  [1367] = 3,
    ACTIONS(111), 1,
      anon_sym_EQ,
    ACTIONS(115), 1,
      anon_sym_COLON,
    ACTIONS(113), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1381] = 1,
    ACTIONS(117), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1391] = 1,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1401] = 3,
    ACTIONS(121), 1,
      anon_sym_EQ,
    ACTIONS(125), 1,
      anon_sym_COLON,
    ACTIONS(123), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1415] = 2,
    ACTIONS(127), 1,
      anon_sym_EQ,
    ACTIONS(129), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1426] = 2,
    ACTIONS(131), 1,
      anon_sym_EQ,
    ACTIONS(133), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1437] = 4,
    ACTIONS(137), 1,
      anon_sym_DOLLAR,
    ACTIONS(139), 1,
      aux_sym_doc_comment_token1,
    STATE(63), 1,
      aux_sym_doc_comment_repeat1,
    ACTIONS(135), 3,
      sym_identifier,
      anon_sym_struct,
      anon_sym_union,
  [1452] = 2,
    ACTIONS(142), 1,
      anon_sym_EQ,
    ACTIONS(144), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1463] = 2,
    ACTIONS(146), 1,
      anon_sym_EQ,
    ACTIONS(148), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1474] = 3,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_struct_repeat1,
    ACTIONS(150), 4,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1487] = 4,
    ACTIONS(157), 1,
      anon_sym_DOLLAR,
    ACTIONS(159), 1,
      aux_sym_doc_comment_token1,
    STATE(63), 1,
      aux_sym_doc_comment_repeat1,
    ACTIONS(155), 3,
      sym_identifier,
      anon_sym_struct,
      anon_sym_union,
  [1502] = 3,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_union_repeat1,
    ACTIONS(161), 4,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1515] = 1,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1523] = 1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1531] = 1,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1539] = 1,
    ACTIONS(172), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1547] = 1,
    ACTIONS(174), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1555] = 1,
    ACTIONS(161), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1563] = 1,
    ACTIONS(176), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1571] = 1,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1579] = 1,
    ACTIONS(180), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1587] = 1,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1595] = 1,
    ACTIONS(184), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1603] = 1,
    ACTIONS(186), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1611] = 1,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1619] = 1,
    ACTIONS(190), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1627] = 1,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1635] = 1,
    ACTIONS(194), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1643] = 1,
    ACTIONS(196), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1651] = 1,
    ACTIONS(198), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1659] = 1,
    ACTIONS(200), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1667] = 1,
    ACTIONS(202), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1675] = 1,
    ACTIONS(150), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1683] = 5,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(89), 1,
      sym_struct_field,
    STATE(107), 1,
      sym_doc_comment,
  [1699] = 1,
    ACTIONS(206), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1707] = 1,
    ACTIONS(208), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1715] = 1,
    ACTIONS(210), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1723] = 5,
    ACTIONS(5), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(212), 1,
      sym_identifier,
    STATE(67), 1,
      aux_sym_doc_comment_repeat1,
    STATE(74), 1,
      sym_union_field,
    STATE(112), 1,
      sym_doc_comment,
  [1739] = 1,
    ACTIONS(214), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1747] = 1,
    ACTIONS(216), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1755] = 1,
    ACTIONS(218), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1763] = 1,
    ACTIONS(220), 5,
      anon_sym_struct,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1771] = 1,
    ACTIONS(222), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1779] = 1,
    ACTIONS(224), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_RBRACE,
      anon_sym_union,
      aux_sym_doc_comment_token1,
  [1787] = 3,
    ACTIONS(226), 1,
      sym_identifier,
    ACTIONS(228), 1,
      anon_sym_struct,
    ACTIONS(230), 1,
      anon_sym_union,
  [1797] = 3,
    ACTIONS(228), 1,
      anon_sym_struct,
    ACTIONS(230), 1,
      anon_sym_union,
    ACTIONS(232), 1,
      sym_identifier,
  [1807] = 2,
    ACTIONS(234), 1,
      anon_sym_struct,
    ACTIONS(236), 1,
      anon_sym_union,
  [1814] = 1,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
  [1818] = 1,
    ACTIONS(240), 1,
      sym_identifier,
  [1822] = 1,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
  [1826] = 1,
    ACTIONS(244), 1,
      sym_identifier,
  [1830] = 1,
    ACTIONS(246), 1,
      anon_sym_EQ,
  [1834] = 1,
    ACTIONS(248), 1,
      sym_identifier,
  [1838] = 1,
    ACTIONS(250), 1,
      anon_sym_LBRACE,
  [1842] = 1,
    ACTIONS(252), 1,
      anon_sym_EQ,
  [1846] = 1,
    ACTIONS(254), 1,
      sym_identifier,
  [1850] = 1,
    ACTIONS(256), 1,
      sym_identifier,
  [1854] = 1,
    ACTIONS(258), 1,
      sym_identifier,
  [1858] = 1,
    ACTIONS(260), 1,
      anon_sym_DOLLAR,
  [1862] = 1,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
  [1866] = 1,
    ACTIONS(264), 1,
      ts_builtin_sym_end,
  [1870] = 1,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
  [1874] = 1,
    ACTIONS(268), 1,
      anon_sym_COLON,
  [1878] = 1,
    ACTIONS(270), 1,
      anon_sym_COLON,
  [1882] = 1,
    ACTIONS(272), 1,
      aux_sym_string_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 110,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 190,
  [SMALL_STATE(10)] = 220,
  [SMALL_STATE(11)] = 240,
  [SMALL_STATE(12)] = 270,
  [SMALL_STATE(13)] = 290,
  [SMALL_STATE(14)] = 320,
  [SMALL_STATE(15)] = 350,
  [SMALL_STATE(16)] = 380,
  [SMALL_STATE(17)] = 410,
  [SMALL_STATE(18)] = 440,
  [SMALL_STATE(19)] = 470,
  [SMALL_STATE(20)] = 500,
  [SMALL_STATE(21)] = 530,
  [SMALL_STATE(22)] = 550,
  [SMALL_STATE(23)] = 570,
  [SMALL_STATE(24)] = 600,
  [SMALL_STATE(25)] = 630,
  [SMALL_STATE(26)] = 660,
  [SMALL_STATE(27)] = 690,
  [SMALL_STATE(28)] = 720,
  [SMALL_STATE(29)] = 745,
  [SMALL_STATE(30)] = 762,
  [SMALL_STATE(31)] = 779,
  [SMALL_STATE(32)] = 803,
  [SMALL_STATE(33)] = 827,
  [SMALL_STATE(34)] = 851,
  [SMALL_STATE(35)] = 875,
  [SMALL_STATE(36)] = 899,
  [SMALL_STATE(37)] = 923,
  [SMALL_STATE(38)] = 947,
  [SMALL_STATE(39)] = 965,
  [SMALL_STATE(40)] = 989,
  [SMALL_STATE(41)] = 1013,
  [SMALL_STATE(42)] = 1031,
  [SMALL_STATE(43)] = 1055,
  [SMALL_STATE(44)] = 1079,
  [SMALL_STATE(45)] = 1097,
  [SMALL_STATE(46)] = 1121,
  [SMALL_STATE(47)] = 1145,
  [SMALL_STATE(48)] = 1169,
  [SMALL_STATE(49)] = 1187,
  [SMALL_STATE(50)] = 1211,
  [SMALL_STATE(51)] = 1235,
  [SMALL_STATE(52)] = 1259,
  [SMALL_STATE(53)] = 1283,
  [SMALL_STATE(54)] = 1301,
  [SMALL_STATE(55)] = 1325,
  [SMALL_STATE(56)] = 1349,
  [SMALL_STATE(57)] = 1367,
  [SMALL_STATE(58)] = 1381,
  [SMALL_STATE(59)] = 1391,
  [SMALL_STATE(60)] = 1401,
  [SMALL_STATE(61)] = 1415,
  [SMALL_STATE(62)] = 1426,
  [SMALL_STATE(63)] = 1437,
  [SMALL_STATE(64)] = 1452,
  [SMALL_STATE(65)] = 1463,
  [SMALL_STATE(66)] = 1474,
  [SMALL_STATE(67)] = 1487,
  [SMALL_STATE(68)] = 1502,
  [SMALL_STATE(69)] = 1515,
  [SMALL_STATE(70)] = 1523,
  [SMALL_STATE(71)] = 1531,
  [SMALL_STATE(72)] = 1539,
  [SMALL_STATE(73)] = 1547,
  [SMALL_STATE(74)] = 1555,
  [SMALL_STATE(75)] = 1563,
  [SMALL_STATE(76)] = 1571,
  [SMALL_STATE(77)] = 1579,
  [SMALL_STATE(78)] = 1587,
  [SMALL_STATE(79)] = 1595,
  [SMALL_STATE(80)] = 1603,
  [SMALL_STATE(81)] = 1611,
  [SMALL_STATE(82)] = 1619,
  [SMALL_STATE(83)] = 1627,
  [SMALL_STATE(84)] = 1635,
  [SMALL_STATE(85)] = 1643,
  [SMALL_STATE(86)] = 1651,
  [SMALL_STATE(87)] = 1659,
  [SMALL_STATE(88)] = 1667,
  [SMALL_STATE(89)] = 1675,
  [SMALL_STATE(90)] = 1683,
  [SMALL_STATE(91)] = 1699,
  [SMALL_STATE(92)] = 1707,
  [SMALL_STATE(93)] = 1715,
  [SMALL_STATE(94)] = 1723,
  [SMALL_STATE(95)] = 1739,
  [SMALL_STATE(96)] = 1747,
  [SMALL_STATE(97)] = 1755,
  [SMALL_STATE(98)] = 1763,
  [SMALL_STATE(99)] = 1771,
  [SMALL_STATE(100)] = 1779,
  [SMALL_STATE(101)] = 1787,
  [SMALL_STATE(102)] = 1797,
  [SMALL_STATE(103)] = 1807,
  [SMALL_STATE(104)] = 1814,
  [SMALL_STATE(105)] = 1818,
  [SMALL_STATE(106)] = 1822,
  [SMALL_STATE(107)] = 1826,
  [SMALL_STATE(108)] = 1830,
  [SMALL_STATE(109)] = 1834,
  [SMALL_STATE(110)] = 1838,
  [SMALL_STATE(111)] = 1842,
  [SMALL_STATE(112)] = 1846,
  [SMALL_STATE(113)] = 1850,
  [SMALL_STATE(114)] = 1854,
  [SMALL_STATE(115)] = 1858,
  [SMALL_STATE(116)] = 1862,
  [SMALL_STATE(117)] = 1866,
  [SMALL_STATE(118)] = 1870,
  [SMALL_STATE(119)] = 1874,
  [SMALL_STATE(120)] = 1878,
  [SMALL_STATE(121)] = 1882,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2), SHIFT_REPEAT(109),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2), SHIFT_REPEAT(105),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2), SHIFT_REPEAT(67),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expr_repeat1, 2),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expr_repeat1, 2), SHIFT_REPEAT(29),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 4, .production_id = 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 5, .production_id = 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 4, .production_id = 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 3, .production_id = 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 2, .production_id = 5),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 1, .production_id = 4),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, .production_id = 9),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 3, .production_id = 7),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_doc_comment_repeat1, 2),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_doc_comment_repeat1, 2), SHIFT_REPEAT(63),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, .production_id = 7),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 4, .production_id = 9),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2), SHIFT_REPEAT(90),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doc_comment, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_comment, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_repeat1, 2),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_repeat1, 2), SHIFT_REPEAT(94),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, .production_id = 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 8, .production_id = 6),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 9, .production_id = 6),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 3, .production_id = 8),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 6, .production_id = 3),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, .production_id = 6),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 5, .production_id = 3),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 6, .production_id = 12),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, .production_id = 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, .production_id = 6),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 4, .production_id = 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 8, .production_id = 3),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, .production_id = 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 6, .production_id = 6),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 6, .production_id = 12),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 8, .production_id = 6),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, .production_id = 3),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 8, .production_id = 3),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 5, .production_id = 11),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 7, .production_id = 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 4, .production_id = 10),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 5, .production_id = 6),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, .production_id = 6),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 5, .production_id = 11),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 7, .production_id = 6),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union, 9, .production_id = 6),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [264] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ziggy_schema(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
