#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 108
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 1
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 18

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_root = 2,
  anon_sym_EQ = 3,
  anon_sym_COMMA = 4,
  anon_sym_AT = 5,
  anon_sym_enum = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_bytes = 9,
  anon_sym_int = 10,
  anon_sym_float = 11,
  anon_sym_bool = 12,
  anon_sym_any = 13,
  anon_sym_unknown = 14,
  anon_sym_null = 15,
  anon_sym_true = 16,
  anon_sym_false = 17,
  anon_sym_LBRACK_RBRACK = 18,
  anon_sym_LBRACE_RBRACE = 19,
  anon_sym_DQUOTE = 20,
  aux_sym_string_token1 = 21,
  sym_number = 22,
  anon_sym_PIPE = 23,
  anon_sym_LBRACK = 24,
  anon_sym_COLON = 25,
  anon_sym_RBRACK = 26,
  anon_sym_QMARK = 27,
  anon_sym_struct = 28,
  aux_sym_doc_comment_token1 = 29,
  sym_schema = 30,
  sym_tag_name = 31,
  sym_enum_definition = 32,
  sym_tag = 33,
  sym_expr = 34,
  sym_default = 35,
  sym_string = 36,
  sym_struct_union = 37,
  sym_map = 38,
  sym_array = 39,
  sym_optional = 40,
  sym_struct = 41,
  sym_struct_field = 42,
  sym_doc_comment = 43,
  aux_sym_schema_repeat1 = 44,
  aux_sym_schema_repeat2 = 45,
  aux_sym_enum_definition_repeat1 = 46,
  aux_sym_struct_union_repeat1 = 47,
  aux_sym_struct_repeat1 = 48,
  aux_sym_doc_comment_repeat1 = 49,
  anon_alias_sym__tag_name = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_root] = "root",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_AT] = "@",
  [anon_sym_enum] = "enum",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_bytes] = "bytes",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_bool] = "bool",
  [anon_sym_any] = "any",
  [anon_sym_unknown] = "unknown",
  [anon_sym_null] = "null",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_number] = "number",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACK] = "]",
  [anon_sym_QMARK] = "\?",
  [anon_sym_struct] = "struct",
  [aux_sym_doc_comment_token1] = "doc_comment_token1",
  [sym_schema] = "schema",
  [sym_tag_name] = "tag_name",
  [sym_enum_definition] = "enum_definition",
  [sym_tag] = "tag",
  [sym_expr] = "expr",
  [sym_default] = "default",
  [sym_string] = "string",
  [sym_struct_union] = "struct_union",
  [sym_map] = "map",
  [sym_array] = "array",
  [sym_optional] = "optional",
  [sym_struct] = "struct",
  [sym_struct_field] = "struct_field",
  [sym_doc_comment] = "doc_comment",
  [aux_sym_schema_repeat1] = "schema_repeat1",
  [aux_sym_schema_repeat2] = "schema_repeat2",
  [aux_sym_enum_definition_repeat1] = "enum_definition_repeat1",
  [aux_sym_struct_union_repeat1] = "struct_union_repeat1",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_doc_comment_repeat1] = "doc_comment_repeat1",
  [anon_alias_sym__tag_name] = "_tag_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_root] = anon_sym_root,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_bytes] = anon_sym_bytes,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_any] = anon_sym_any,
  [anon_sym_unknown] = anon_sym_unknown,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_number] = sym_number,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_struct] = anon_sym_struct,
  [aux_sym_doc_comment_token1] = aux_sym_doc_comment_token1,
  [sym_schema] = sym_schema,
  [sym_tag_name] = sym_tag_name,
  [sym_enum_definition] = sym_enum_definition,
  [sym_tag] = sym_tag,
  [sym_expr] = sym_expr,
  [sym_default] = sym_default,
  [sym_string] = sym_string,
  [sym_struct_union] = sym_struct_union,
  [sym_map] = sym_map,
  [sym_array] = sym_array,
  [sym_optional] = sym_optional,
  [sym_struct] = sym_struct,
  [sym_struct_field] = sym_struct_field,
  [sym_doc_comment] = sym_doc_comment,
  [aux_sym_schema_repeat1] = aux_sym_schema_repeat1,
  [aux_sym_schema_repeat2] = aux_sym_schema_repeat2,
  [aux_sym_enum_definition_repeat1] = aux_sym_enum_definition_repeat1,
  [aux_sym_struct_union_repeat1] = aux_sym_struct_union_repeat1,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_doc_comment_repeat1] = aux_sym_doc_comment_repeat1,
  [anon_alias_sym__tag_name] = anon_alias_sym__tag_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_root] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bytes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_any] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unknown] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doc_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_default] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_union] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_schema_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_schema_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_union_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_doc_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym__tag_name] = {
    .visible = true,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_default = 1,
  field_docs = 2,
  field_expr = 3,
  field_key = 4,
  field_name = 5,
  field_root = 6,
  field_structs = 7,
  field_tags = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_default] = "default",
  [field_docs] = "docs",
  [field_expr] = "expr",
  [field_key] = "key",
  [field_name] = "name",
  [field_root] = "root",
  [field_structs] = "structs",
  [field_tags] = "tags",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 3},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 4},
  [9] = {.index = 17, .length = 4},
  [10] = {.index = 21, .length = 1},
  [11] = {.index = 22, .length = 5},
  [12] = {.index = 27, .length = 3},
  [13] = {.index = 30, .length = 2},
  [14] = {.index = 32, .length = 2},
  [15] = {.index = 34, .length = 3},
  [16] = {.index = 37, .length = 4},
  [17] = {.index = 41, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_root, 2},
  [1] =
    {field_root, 2},
    {field_tags, 3},
  [3] =
    {field_root, 2},
    {field_structs, 3},
  [5] =
    {field_root, 2},
    {field_tags, 3},
    {field_tags, 4},
  [8] =
    {field_root, 2},
    {field_structs, 4},
    {field_tags, 3},
  [11] =
    {field_expr, 2},
    {field_name, 0},
  [13] =
    {field_root, 2},
    {field_structs, 5},
    {field_tags, 3},
    {field_tags, 4},
  [17] =
    {field_root, 2},
    {field_tags, 3},
    {field_tags, 4},
    {field_tags, 5},
  [21] =
    {field_name, 1},
  [22] =
    {field_root, 2},
    {field_structs, 6},
    {field_tags, 3},
    {field_tags, 4},
    {field_tags, 5},
  [27] =
    {field_docs, 0},
    {field_expr, 3},
    {field_name, 1},
  [30] =
    {field_docs, 0},
    {field_name, 2},
  [32] =
    {field_key, 0},
    {field_value, 2},
  [34] =
    {field_docs, 0},
    {field_key, 1},
    {field_value, 3},
  [37] =
    {field_default, 3},
    {field_default, 4},
    {field_key, 0},
    {field_value, 2},
  [41] =
    {field_default, 4},
    {field_default, 5},
    {field_docs, 0},
    {field_key, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [1] = anon_alias_sym__tag_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == ',') ADVANCE(8);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '?') ADVANCE(23);
      if (lookahead == '@') ADVANCE(9);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '|') ADVANCE(18);
      if (lookahead == '}') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == '{') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(13);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_doc_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'b') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(7);
      if (lookahead == 's') ADVANCE(8);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(12);
      if (lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'y') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(34);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_any);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_root);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(48);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_bytes);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 49:
      if (lookahead == 'w') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_unknown);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 15},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_root] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_bytes] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_any] = ACTIONS(1),
    [anon_sym_unknown] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [aux_sym_doc_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_schema] = STATE(99),
    [anon_sym_root] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_QMARK,
    STATE(48), 1,
      sym_expr,
    STATE(34), 5,
      sym_tag_name,
      sym_struct_union,
      sym_map,
      sym_array,
      sym_optional,
    ACTIONS(9), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      anon_sym_unknown,
  [31] = 7,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_QMARK,
    STATE(10), 1,
      sym_expr,
    STATE(34), 5,
      sym_tag_name,
      sym_struct_union,
      sym_map,
      sym_array,
      sym_optional,
    ACTIONS(9), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      anon_sym_unknown,
  [62] = 7,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_QMARK,
    STATE(40), 1,
      sym_expr,
    STATE(34), 5,
      sym_tag_name,
      sym_struct_union,
      sym_map,
      sym_array,
      sym_optional,
    ACTIONS(9), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      anon_sym_unknown,
  [93] = 7,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_QMARK,
    STATE(53), 1,
      sym_expr,
    STATE(34), 5,
      sym_tag_name,
      sym_struct_union,
      sym_map,
      sym_array,
      sym_optional,
    ACTIONS(9), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      anon_sym_unknown,
  [124] = 7,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_QMARK,
    STATE(32), 1,
      sym_expr,
    STATE(34), 5,
      sym_tag_name,
      sym_struct_union,
      sym_map,
      sym_array,
      sym_optional,
    ACTIONS(9), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      anon_sym_unknown,
  [155] = 7,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_QMARK,
    STATE(42), 1,
      sym_expr,
    STATE(34), 5,
      sym_tag_name,
      sym_struct_union,
      sym_map,
      sym_array,
      sym_optional,
    ACTIONS(9), 6,
      anon_sym_bytes,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_any,
      anon_sym_unknown,
  [186] = 9,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(66), 1,
      sym_tag,
    STATE(78), 1,
      sym_doc_comment,
    STATE(94), 1,
      sym_tag_name,
    STATE(44), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [215] = 9,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(66), 1,
      sym_tag,
    STATE(78), 1,
      sym_doc_comment,
    STATE(94), 1,
      sym_tag_name,
    STATE(30), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [244] = 9,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_tag,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(78), 1,
      sym_doc_comment,
    STATE(94), 1,
      sym_tag_name,
    STATE(46), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [273] = 3,
    ACTIONS(27), 1,
      anon_sym_PIPE,
    STATE(14), 1,
      aux_sym_struct_union_repeat1,
    ACTIONS(25), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [289] = 8,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 1,
      anon_sym_struct,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(70), 1,
      sym_struct_field,
    STATE(82), 1,
      sym_doc_comment,
    STATE(45), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [315] = 8,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_struct,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(70), 1,
      sym_struct_field,
    STATE(82), 1,
      sym_doc_comment,
    STATE(33), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [341] = 3,
    ACTIONS(27), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_struct_union_repeat1,
    ACTIONS(37), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [357] = 8,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(39), 1,
      anon_sym_COMMA,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_struct_repeat1,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(35), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [383] = 8,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(43), 1,
      anon_sym_COMMA,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      aux_sym_struct_repeat1,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(39), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [409] = 8,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_struct,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(70), 1,
      sym_struct_field,
    STATE(82), 1,
      sym_doc_comment,
    STATE(39), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [435] = 4,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    STATE(56), 1,
      sym_default,
    STATE(68), 1,
      sym_string,
    ACTIONS(47), 6,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_RBRACE,
      sym_number,
  [453] = 8,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_schema_repeat1,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(36), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [479] = 8,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_struct,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      sym_struct_field,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(82), 1,
      sym_doc_comment,
    STATE(41), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [505] = 8,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(57), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(54), 1,
      aux_sym_schema_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(44), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [531] = 3,
    ACTIONS(61), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_struct_union_repeat1,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [547] = 8,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_struct_repeat1,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(45), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [573] = 4,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    STATE(68), 1,
      sym_string,
    STATE(72), 1,
      sym_default,
    ACTIONS(47), 6,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LBRACE_RBRACE,
      sym_number,
  [591] = 8,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(66), 1,
      anon_sym_COMMA,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_struct_repeat1,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(43), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [617] = 8,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_struct,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      sym_struct_field,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(82), 1,
      sym_doc_comment,
    STATE(31), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [643] = 8,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_struct,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(70), 1,
      sym_struct_field,
    STATE(82), 1,
      sym_doc_comment,
    STATE(38), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [669] = 6,
    ACTIONS(76), 1,
      anon_sym_struct,
    ACTIONS(79), 1,
      aux_sym_doc_comment_token1,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [690] = 1,
    ACTIONS(59), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [701] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [721] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [741] = 1,
    ACTIONS(84), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [751] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [771] = 1,
    ACTIONS(25), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [781] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [801] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [821] = 1,
    ACTIONS(90), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [831] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [851] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [871] = 1,
    ACTIONS(94), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [881] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [901] = 1,
    ACTIONS(96), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [911] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [931] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [951] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [971] = 6,
    ACTIONS(17), 1,
      anon_sym_struct,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(107), 1,
      sym_doc_comment,
    STATE(28), 2,
      sym_struct,
      aux_sym_schema_repeat2,
  [991] = 6,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(66), 1,
      sym_tag,
    STATE(84), 1,
      sym_doc_comment,
    STATE(94), 1,
      sym_tag_name,
  [1010] = 2,
    ACTIONS(102), 1,
      anon_sym_EQ,
    ACTIONS(104), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1020] = 5,
    ACTIONS(19), 1,
      aux_sym_doc_comment_token1,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(52), 1,
      aux_sym_doc_comment_repeat1,
    STATE(70), 1,
      sym_struct_field,
    STATE(98), 1,
      sym_doc_comment,
  [1036] = 4,
    ACTIONS(110), 1,
      anon_sym_AT,
    ACTIONS(112), 1,
      aux_sym_doc_comment_token1,
    STATE(50), 1,
      aux_sym_doc_comment_repeat1,
    ACTIONS(108), 2,
      sym_identifier,
      anon_sym_struct,
  [1050] = 3,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_struct_repeat1,
    ACTIONS(118), 3,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1062] = 4,
    ACTIONS(122), 1,
      anon_sym_AT,
    ACTIONS(124), 1,
      aux_sym_doc_comment_token1,
    STATE(50), 1,
      aux_sym_doc_comment_repeat1,
    ACTIONS(120), 2,
      sym_identifier,
      anon_sym_struct,
  [1076] = 2,
    ACTIONS(126), 1,
      anon_sym_EQ,
    ACTIONS(128), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1086] = 3,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_schema_repeat1,
    ACTIONS(130), 3,
      ts_builtin_sym_end,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1098] = 1,
    ACTIONS(135), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1105] = 1,
    ACTIONS(137), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1112] = 1,
    ACTIONS(139), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1119] = 1,
    ACTIONS(141), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1126] = 1,
    ACTIONS(143), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1133] = 1,
    ACTIONS(145), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1140] = 1,
    ACTIONS(147), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1147] = 1,
    ACTIONS(149), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1154] = 1,
    ACTIONS(151), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1161] = 1,
    ACTIONS(153), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1168] = 1,
    ACTIONS(155), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1175] = 1,
    ACTIONS(130), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1182] = 1,
    ACTIONS(157), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1189] = 1,
    ACTIONS(159), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1196] = 1,
    ACTIONS(161), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1203] = 1,
    ACTIONS(118), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1210] = 1,
    ACTIONS(163), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1217] = 1,
    ACTIONS(165), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1224] = 1,
    ACTIONS(167), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1231] = 1,
    ACTIONS(169), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1238] = 1,
    ACTIONS(171), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_struct,
      aux_sym_doc_comment_token1,
  [1245] = 3,
    ACTIONS(173), 1,
      anon_sym_enum,
    ACTIONS(175), 1,
      anon_sym_bytes,
    STATE(55), 1,
      sym_enum_definition,
  [1255] = 3,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym_enum_definition_repeat1,
  [1265] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(181), 1,
      anon_sym_struct,
    STATE(105), 1,
      sym_tag_name,
  [1275] = 3,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(77), 1,
      aux_sym_enum_definition_repeat1,
  [1285] = 3,
    ACTIONS(173), 1,
      anon_sym_enum,
    ACTIONS(187), 1,
      anon_sym_bytes,
    STATE(67), 1,
      sym_enum_definition,
  [1295] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym_enum_definition_repeat1,
  [1305] = 2,
    ACTIONS(194), 1,
      sym_identifier,
    ACTIONS(196), 1,
      anon_sym_struct,
  [1312] = 2,
    ACTIONS(198), 1,
      sym_identifier,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
  [1319] = 2,
    ACTIONS(7), 1,
      anon_sym_AT,
    STATE(105), 1,
      sym_tag_name,
  [1326] = 2,
    ACTIONS(202), 1,
      anon_sym_COLON,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
  [1333] = 2,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    ACTIONS(198), 1,
      sym_identifier,
  [1340] = 1,
    ACTIONS(192), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1345] = 1,
    ACTIONS(206), 1,
      aux_sym_string_token1,
  [1349] = 1,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
  [1353] = 1,
    ACTIONS(210), 1,
      sym_identifier,
  [1357] = 1,
    ACTIONS(212), 1,
      anon_sym_COLON,
  [1361] = 1,
    ACTIONS(214), 1,
      sym_identifier,
  [1365] = 1,
    ACTIONS(216), 1,
      sym_identifier,
  [1369] = 1,
    ACTIONS(218), 1,
      anon_sym_EQ,
  [1373] = 1,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
  [1377] = 1,
    ACTIONS(222), 1,
      anon_sym_EQ,
  [1381] = 1,
    ACTIONS(224), 1,
      sym_identifier,
  [1385] = 1,
    ACTIONS(226), 1,
      sym_identifier,
  [1389] = 1,
    ACTIONS(228), 1,
      ts_builtin_sym_end,
  [1393] = 1,
    ACTIONS(230), 1,
      anon_sym_COLON,
  [1397] = 1,
    ACTIONS(198), 1,
      sym_identifier,
  [1401] = 1,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
  [1405] = 1,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
  [1409] = 1,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
  [1413] = 1,
    ACTIONS(238), 1,
      anon_sym_EQ,
  [1417] = 1,
    ACTIONS(240), 1,
      sym_identifier,
  [1421] = 1,
    ACTIONS(181), 1,
      anon_sym_struct,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 155,
  [SMALL_STATE(8)] = 186,
  [SMALL_STATE(9)] = 215,
  [SMALL_STATE(10)] = 244,
  [SMALL_STATE(11)] = 273,
  [SMALL_STATE(12)] = 289,
  [SMALL_STATE(13)] = 315,
  [SMALL_STATE(14)] = 341,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 383,
  [SMALL_STATE(17)] = 409,
  [SMALL_STATE(18)] = 435,
  [SMALL_STATE(19)] = 453,
  [SMALL_STATE(20)] = 479,
  [SMALL_STATE(21)] = 505,
  [SMALL_STATE(22)] = 531,
  [SMALL_STATE(23)] = 547,
  [SMALL_STATE(24)] = 573,
  [SMALL_STATE(25)] = 591,
  [SMALL_STATE(26)] = 617,
  [SMALL_STATE(27)] = 643,
  [SMALL_STATE(28)] = 669,
  [SMALL_STATE(29)] = 690,
  [SMALL_STATE(30)] = 701,
  [SMALL_STATE(31)] = 721,
  [SMALL_STATE(32)] = 741,
  [SMALL_STATE(33)] = 751,
  [SMALL_STATE(34)] = 771,
  [SMALL_STATE(35)] = 781,
  [SMALL_STATE(36)] = 801,
  [SMALL_STATE(37)] = 821,
  [SMALL_STATE(38)] = 831,
  [SMALL_STATE(39)] = 851,
  [SMALL_STATE(40)] = 871,
  [SMALL_STATE(41)] = 881,
  [SMALL_STATE(42)] = 901,
  [SMALL_STATE(43)] = 911,
  [SMALL_STATE(44)] = 931,
  [SMALL_STATE(45)] = 951,
  [SMALL_STATE(46)] = 971,
  [SMALL_STATE(47)] = 991,
  [SMALL_STATE(48)] = 1010,
  [SMALL_STATE(49)] = 1020,
  [SMALL_STATE(50)] = 1036,
  [SMALL_STATE(51)] = 1050,
  [SMALL_STATE(52)] = 1062,
  [SMALL_STATE(53)] = 1076,
  [SMALL_STATE(54)] = 1086,
  [SMALL_STATE(55)] = 1098,
  [SMALL_STATE(56)] = 1105,
  [SMALL_STATE(57)] = 1112,
  [SMALL_STATE(58)] = 1119,
  [SMALL_STATE(59)] = 1126,
  [SMALL_STATE(60)] = 1133,
  [SMALL_STATE(61)] = 1140,
  [SMALL_STATE(62)] = 1147,
  [SMALL_STATE(63)] = 1154,
  [SMALL_STATE(64)] = 1161,
  [SMALL_STATE(65)] = 1168,
  [SMALL_STATE(66)] = 1175,
  [SMALL_STATE(67)] = 1182,
  [SMALL_STATE(68)] = 1189,
  [SMALL_STATE(69)] = 1196,
  [SMALL_STATE(70)] = 1203,
  [SMALL_STATE(71)] = 1210,
  [SMALL_STATE(72)] = 1217,
  [SMALL_STATE(73)] = 1224,
  [SMALL_STATE(74)] = 1231,
  [SMALL_STATE(75)] = 1238,
  [SMALL_STATE(76)] = 1245,
  [SMALL_STATE(77)] = 1255,
  [SMALL_STATE(78)] = 1265,
  [SMALL_STATE(79)] = 1275,
  [SMALL_STATE(80)] = 1285,
  [SMALL_STATE(81)] = 1295,
  [SMALL_STATE(82)] = 1305,
  [SMALL_STATE(83)] = 1312,
  [SMALL_STATE(84)] = 1319,
  [SMALL_STATE(85)] = 1326,
  [SMALL_STATE(86)] = 1333,
  [SMALL_STATE(87)] = 1340,
  [SMALL_STATE(88)] = 1345,
  [SMALL_STATE(89)] = 1349,
  [SMALL_STATE(90)] = 1353,
  [SMALL_STATE(91)] = 1357,
  [SMALL_STATE(92)] = 1361,
  [SMALL_STATE(93)] = 1365,
  [SMALL_STATE(94)] = 1369,
  [SMALL_STATE(95)] = 1373,
  [SMALL_STATE(96)] = 1377,
  [SMALL_STATE(97)] = 1381,
  [SMALL_STATE(98)] = 1385,
  [SMALL_STATE(99)] = 1389,
  [SMALL_STATE(100)] = 1393,
  [SMALL_STATE(101)] = 1397,
  [SMALL_STATE(102)] = 1401,
  [SMALL_STATE(103)] = 1405,
  [SMALL_STATE(104)] = 1409,
  [SMALL_STATE(105)] = 1413,
  [SMALL_STATE(106)] = 1417,
  [SMALL_STATE(107)] = 1421,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 5, .production_id = 5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 6, .production_id = 9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 3, .production_id = 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_union, 2),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 4, .production_id = 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_union_repeat1, 2),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_union_repeat1, 2), SHIFT_REPEAT(90),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_schema_repeat2, 2),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat2, 2), SHIFT_REPEAT(92),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat2, 2), SHIFT_REPEAT(52),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 7, .production_id = 11),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 5, .production_id = 6),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 2, .production_id = 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 6, .production_id = 8),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 4, .production_id = 4),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, .production_id = 15),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_doc_comment_repeat1, 2),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_doc_comment_repeat1, 2), SHIFT_REPEAT(50),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2), SHIFT_REPEAT(49),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doc_comment, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_comment, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, .production_id = 14),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2), SHIFT_REPEAT(47),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, .production_id = 12),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 6, .production_id = 17),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_definition, 6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, .production_id = 10),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, .production_id = 10),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, .production_id = 13),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, .production_id = 10),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 9, .production_id = 13),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_definition, 5),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5, .production_id = 13),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, .production_id = 7),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, .production_id = 10),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 8, .production_id = 13),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 5, .production_id = 16),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_definition, 4),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 8, .production_id = 10),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 6, .production_id = 13),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_definition_repeat1, 2), SHIFT_REPEAT(101),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_definition_repeat1, 2),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [228] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ziggy_schema(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
